### ISSUE TITLE
Auto importing components plugin makes the app load forever

### ISSUE THREAD

**Issue by kn0wn** [antfu/vitesse#10]
Hi antfu,

I was having some issues trying to get the vitesse working properly, where when running pnpm dev it would forever be in a loading state. I looked around and noticed this in the network tab.

![firefox_yrHW8EUGhj](https://user-images.githubusercontent.com/59017897/91214387-e7086e00-e70a-11ea-94b3-5f40db1cab3b.png)

So I then removed the plugin from `vite.config.ts` and reloaded the app it loaded fine.

Browser: Firefox 79.0 
Operating System: Windows 10
Node: v12.18.2

**Comment by kn0wn** [comment]
So I have just done another fresh install and it is now saying the request is blocked

![firefox_b31iGqMP70](https://user-images.githubusercontent.com/59017897/91215099-efad7400-e70b-11ea-8149-028272aaa6ad.png)

The blocked status goes away when I rename the Footer component to BottomFooter, but it will still load forever

**Comment by antfu** [comment]
There is a conflict for vite-plugin-components when aliases are set. Working on the fix.

**Comment by antfu** [comment]
Please upgrade `vite-plugin-components` to v0.2.10 and pass the alias to its options

https://github.com/antfu/vitesse/blob/7fa1b1556a2537300be3018d48371d7a25f42406/vite.config.ts#L15-L19

Thanks :)
