### ISSUE TITLE
PWA / Workbox configuration on the NodeJS / Express server

### ISSUE THREAD

**Issue by spokospace** [antfu/vitesse#100]
At the outset, I would like to thank you for this starter template. It's great! 
However, I cannot cope with the PWA configuration. Don't know how to create sw.js or how to connect it with Google Workbox.

I installed this packages:
```
npm install workbox-core workbox-precaching workbox-routing workbox-strategies workbox-cacheable-response workbox-expiration workbox-window
npm install workbox-cli -D
```
bud I don't have idea what i need to do next.. :(

**Comment by userquin** [comment]
@spokospace you don't need to install anything, just run `pnpm run build` and `VitePWA` plugin will create for you `sw.js` on `dist` folder with `index.html` modified to install `sw.js`.

In `dev` mode, it is not generated (`sw.js`), only for `build`, see [this issue](https://github.com/antfu/vite-plugin-pwa/issues/26) 

If you want to use your own `sw.js` file, you must go to [VitePWA repository](https://github.com/antfu/vite-plugin-pwa) to check available options. There are `WIP` features, so you cannot use certain options, see opened issues there.

You can see how to use `workbox` [here](https://github.com/antfu/vite-plugin-pwa/issues/33#issuecomment-797814153).

To test on your own `node/express` server, just use the dist folder (all `pwa` stuff are client side, you cannot use it on server side).

**Comment by userquin** [comment]
@spokospace you can also run the app with `https`, run this from the root directory:
`pnpm run build && pnpm run preview-https`

This will ask you about installing a certificate (that will be generated for you), confirm installation on OS (keychain on macosx and certificate manager on windows) and open `https://localhost` on chrome, for example.

I forgot `localhost-https` `dev dependency` has been included on `package.json`.
