### ISSUE TITLE
Markdown Meta + Head

### ISSUE THREAD

**Issue by xemoka** [antfu/vitesse#103]
Hello, 

I'm trying to get the "meta" key of the frontmatter in markdown files hoisted up to the route level, currently a `meta` yaml keyword in a `.md` file is ignored, and a 

```
<route>
meta:
  customMeta: "value"
</route>
```

is required elsewhere in the markdown file; perhaps I'm missing something? How could you control the layout that generates the markdown without a separate <route> component? 

One could provide a wrapper .vue for vite-plugin-md that hoists the meta up, but, again, I have a feeling I'm missing something. 

Thanks.

**Comment by hannoeru** [comment]
You need to set `routeBlockLang: 'yaml'` in `vite.config.ts`'s Pages() plugin options.
or use lang attr like:

```
<route lang="yaml">
meta:
  customMeta: "value"
</route>
```

**Comment by xemoka** [comment]
Yes, sorry, I do have `routeBlockLang: 'yaml'` configured; what I'm after is that the `meta` attribute in the frontmatter of the markdown file to get hoisted up into the route _instead_ of having to both define frontmatter and use the `<route>` component: I'm after all configuration in the markdown frontmatter.

**Comment by hannoeru** [comment]
@antfu should I add a markdown frontmatter parser to vite-plugin-pages? or we can have a resolver from vite-plugin-md? WDYT

**Comment by antfu** [comment]
For me, I am doing another way around, I defined meta in the frontmatter where `vite-plugin-md` could infer them to the head with `enabledHead: true`. Then I apply frontmatter to the route's meta for other route-based logics.

You can how I do it on my site here:

https://github.com/antfu/antfu.me/blob/9f0434ea0c06699f1e9f2b31c2a107dc6d3b50e9/vite.config.ts#L58-L60
https://github.com/antfu/antfu.me/blob/9f0434ea0c06699f1e9f2b31c2a107dc6d3b50e9/vite.config.ts#L70

Hope that works for you

**Comment by xemoka** [comment]
Thank you, that fits exactly where I thought I was missing something.
