### ISSUE TITLE
Uncaught ReferenceError: __DEFINES__ is not defined

### ISSUE THREAD

**Issue by alijuniorbr** [antfu/vitesse#105]
just `use this template` and created new repo on my github

then run
`git clone https://github.com/alijuniorbr/vitesse.git` 

afted done, run
`cd vitesse`
`pnpm i`
`pnpm dev`

the browser open at [http://localhost:3333/](http://localhost:3333/ ) but the page are blank and the console shows this error

Uncaught ReferenceError: __DEFINES__ is not defined
    at env.js:16

![image](https://user-images.githubusercontent.com/63268146/112774267-84b07c80-900f-11eb-9abc-173ee17d8c1d.png)

**Comment by alijuniorbr** [comment]
the console shows no error

![image](https://user-images.githubusercontent.com/63268146/112774354-d0fbbc80-900f-11eb-8be2-71853ddc99f3.png)

**Comment by hannoeru** [comment]
I think is not related to this repo, can you try to open it with incognito mode?

**Comment by alijuniorbr** [comment]
> I think this is not related to this repo, can you try to open it with incognito mode?

open with same error

![image](https://user-images.githubusercontent.com/63268146/112785270-00b7be00-902a-11eb-9c61-ec87d441cb01.png)

**Comment by alijuniorbr** [comment]
only to make it clear, I deleted the `node_modules` folder, and deleted `pnpm-lock.yaml`
so run:
`npm i` and `npm run dev` and the result was:

![image](https://user-images.githubusercontent.com/63268146/112786786-63f71f80-902d-11eb-9381-f764ba89e762.png)

so the problem apparently is with the `pnpm`

as a workaround I'm using `npm`, but I would like to resolve this issue

thanks in advance

**Comment by antfu** [comment]
We are using `pnpm` and have never faced this issue. Can you please do more checks or provide more info for this, for example, what's your pnpm/node/os versions?

**Comment by alijuniorbr** [comment]
![image](https://user-images.githubusercontent.com/63268146/113098070-5b8a1a80-91ce-11eb-9670-e3341c852652.png)
