### ISSUE TITLE
[question] How can I make detection of browser language?

### ISSUE THREAD

**Issue by lolzzz992** [antfu/vitesse#107]
When I used vue-cli , I just did locale: window.localStorage.Language || window.localStorage.sessionStorage || window.navigator.language, but with this vite template it's doesn't seem to work.
And well I think even if it will be somehow fixed it will cause ReferenceError: window is not defined on compile and it will, since I tested. 
Code works fine but it does nothing, what I tried to make

main.ts >

import eng from '/locales/en.yml'
import jpn from '/locales/jp.yml'
import rus from '/locales/ru.yml'
import { createI18n } from 'vue-i18n'

const i18n = createI18n({
  locale: window.localStorage.Language || window.localStorage.sessionStorage || window.navigator.language, 
  fallbackLocale: 'en',
  messages: {
    en: eng,
    ru: rus,
    jp: jpn,
},
})

And I did exactly as I made before but now it doesn't work as well as causing error on compile. Is there any way to detect browser language? I know messages string is useless but it may help...

I really need to know, have no idea where to ask

**Comment by antfu** [comment]
Try this: https://vueuse.org/core/usePreferredLanguages/

The error might because in SSG there is no `window` object, which you will need to check it before using it,

**Comment by lolzzz992** [comment]
Don't sure how to use it properly, I trying now, it's seems more likely as solution, but don't sure how

**Comment by hannoeru** [comment]
It return `Ref`, so you need add `.value` in the end to get the value of it.
https://v3.vuejs.org/api/refs-api.html#refs

**Comment by lolzzz992** [comment]
Ref

> It return `Ref`, so you need add `.value` in the end to get the value of it.
> https://v3.vuejs.org/api/refs-api.html#refs

Whatever I do I get:
Property 'value' does not exist on type '(options?: ConfiguratableWindo | undefined) => Ref<readonly string[]>'.

**Comment by lolzzz992** [comment]
I fixed it. I created a code in main.ts while there was already file with settings for i18n... oops. Main problem wasn't in that thought.
usePreferredLanguages().value[0] was the solution.

To made this work:
go to **src/modules/i18n.ts**

and add
`import { usePreferredLanguages } from '@vueuse/core'`
replace locale: 'en' with
`locale: usePreferredLanguages().value[0]`
(you can also add fallbackLocale: 'en', to fix missing translation, funny enough that setting didn't worked for me when I used my own template and vue-cli, but here it works fine )

Should be look like this:
```
import { createI18n } from 'vue-i18n'
import { UserModule } from '~/types'
import { usePreferredLanguages } from '@vueuse/core'

// import i18n resources
// https://vitejs.dev/guide/features.html#glob-import
const messages = Object.fromEntries(
  Object.entries(
    import.meta.globEager('../../locales/*.y(a)?ml'))
    .map(([key, value]) => {
      const yaml = key.endsWith('.yaml')
      return [key.slice(14, yaml ? -5 : -4), value.default]
    }),
)

export const install: UserModule = ({ app }) => {
  const i18n = createI18n({
    legacy: false,
    locale: usePreferredLanguages().value[0],
    messages,
  })

  app.use(i18n)
}
```

:D
