### ISSUE TITLE
createApp vs app?

### ISSUE THREAD

**Issue by mariusa** [antfu/vitesse#109]
Hi, thanks for this great template!

I'm confused by this
https://github.com/antfu/vitesse/blob/776494a657dc297c2615d060592fd93ea086dc80/src/main.ts#L12

1. Looks like `ViteSSG` is the equivalent of vue's `createApp`. If so, it would be more clear to say `const app = ViteSSG(...'
2. Trying to register a global component doesn't work 
```
export const createApp = ViteSSG(
    App,
    { routes },
    (ctx) => {
        // install all modules under `modules/`
        Object.values(import.meta.globEager('./modules/*.ts')).map(i => i.install?.(ctx))
    },
)
console.log('createApp', createApp)
createApp.component('set', set)
```
gives `Uncaught TypeError: createApp.component is not a function`
How should that work, please?

3. Why is `export` needed?

**Comment by antfu** [comment]
```ts
export const createApp = ViteSSG(
    App,
    { routes },
    (ctx) => {
        // install all modules under `modules/`
        Object.values(import.meta.globEager('./modules/*.ts')).map(i => i.install?.(ctx))
        const { app } = ctx
        app.component('foo', Foo)
    },
)
```

`export` and `createApp` it's because Vite SSG needs to import it in the server build, create an App and do the SSR.
https://github.com/antfu/vite-ssg#single-page-ssg

**Comment by mariusa** [comment]
Thanks!

**Comment by dexcell** [comment]
Can we have this in docs on how to register component globaly since it's pretty commmon stuff to save some time.
````
const { app } = ctx
app.component('foo', Foo)
````

**Comment by mariusa** [comment]
My understanding: there's no need for `app.component('foo', Foo)` as vitesse uses https://github.com/antfu/vite-plugin-components for components in `src/components`
but I'm not sure how that works for imported components from other packages installed via npm

**Comment by kissu** [comment]
I am also wondering how we could achieve a global registration from within a `.vue` component, rather than in `main.ts`.
The idea would be to create some dynamic components thanks to the payload of an HTTP call and depending on the actual route the user is on.
