### ISSUE TITLE
Why are there Google Analytics dependencies used?

### ISSUE THREAD

**Issue by qx-775** [antfu/vitesse#113]
Hi,

First off, this is an amazing project. Thank you for your work.

## Found google analytics in source code
Running the application shows that Google analytics is found as a technology.
Looking at the pnpm file
```yaml

  /workbox-google-analytics/6.1.2:
    resolution: {integrity: sha512-7mO/gMms1yivnoVPnm8LXYHV2SsHBxTijYNXx032nzMX0gpBKJfRHmNvZDVRvn2L6YRxFiMg0x9JuHe2b2wSeg==}
    dependencies:
      workbox-background-sync: 6.1.2
      workbox-core: 6.1.2
      workbox-routing: 6.1.2
      workbox-strategies: 6.1.2
    dev: true
```

We can find that google analytics are enabled during dev? Why? 
Looking at the workbox-google-analytics website it says:
`Workbox Google Analytics solves this problem for Google Analytics users by leveraging Service Worker's ability to detect failed requests.`

 Having google analytics built in is bad for privacy. I do not understand wat this solves or what you use it for.

## Question

Could you clarify or perhaps remove this dependency?
---
Cheers!

**Comment by userquin** [comment]
@qx-775 this dependency comes from `vite-plugin-pwa`, but it is not used when building the `service worker`: the plugin will need `workbox-*` dependencies and so ` workbox-google-analytics` is there. The plugin will not bundle the dependency, in fact it is deactivated by default and so there is no problem with privacy (unless you activate analytics): see https://github.com/antfu/vite-plugin-pwa/blob/master/src/options.ts#L78.

**Comment by qx-775** [comment]
Alrighty, thanks for your answer. I my own vitesse project I removed it without problems. Cheers
