### ISSUE TITLE
[feature] Add typescipt checks for vue templates at build time

### ISSUE THREAD

**Issue by robbertvc** [antfu/vitesse#114]
At the moment the vscode Volar extension catches type errors in SFC templates brilliantly. Is there any way to make a `pnpm build` fail if there are type errors in a template?

![image](https://user-images.githubusercontent.com/6222998/116244709-78cbed80-a768-11eb-9fba-e16ae9d4c75f.png)

**Comment by antfu** [comment]
Open for PR to adding this
https://github.com/vitejs/vite/blob/7cd8d7832e12e2facf7dfc163320a8798e19c6fd/packages/create-app/template-vue-ts/package.json#L6

**Comment by robbertvc** [comment]
I had to turn of incremental ts compilation though. Is that an issue?

**Comment by antfu** [comment]
Yeah, turning it off it fine. We don't need it actually.
