### ISSUE TITLE
build doesn't finish

### ISSUE THREAD

**Issue by Septias** [antfu/vitesse#12]
My new vitesse project https://github.com/Septias/hot-potato gets stuck with 'Building for production...' and doesn't finish the build step. I tried it on my laptop and pc but both won't finish building for production. 
I'm using VSCode Terminal which utilizes PowerShell on Windows x64.

**Comment by antfu** [comment]
Could you bump the version of `vite-plugin-components` and try again?

**Comment by Septias** [comment]
okay, that solved it thanks :^)
