### ISSUE TITLE
[feature request] Add Dockerfile

### ISSUE THREAD

**Issue by qx-775** [antfu/vitesse#120]
# Feature request
Hi, could you add a Dockerfile which dockerizes the vue js app? I currently have in my project a vue 3 dockerfile but it takes over 45! minutes to create the container because `npm install` inside the docker contaienr is very slow. Do you have an idea to speed up to create a container? I have done all the 'speed up npm install inside a docker container' tutorials without avail.

My dockerfile to dockerize a vue js 3 vitesse tailwind project (feel free to copy)
```yaml
# develop stage
FROM node:15-alpine as develop-stage
WORKDIR /usr/src/app
CMD cd /usr/src/app
COPY package*.json ./
#RUN npm install --prefer-offline --no-audit --progress=false
RUN npm install
COPY . .

# build stage
FROM develop-stage as build-stage
RUN npm run build

# production stage
FROM nginx:alpine as production-stage
COPY --from=build-stage /usr/src/app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

**Comment by hannoeru** [comment]
We are using pnpm as package manager

Example:

```Dockerfile
# build stage
FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package.json pnpm*.yaml ./
RUN npm install -g pnpm
RUN pnpm install
COPY . .
RUN pnpm run build

# production stage
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
```

This works will on my environment.
