### ISSUE TITLE
Build process doesn't exit

### ISSUE THREAD

**Issue by Ragura** [antfu/vitesse#130]
Finished building my app in record time with this template, amazing! I fell in love with Vite too...

But I'm having a problem deploying to Netlify due to the build process, started with `pnpm run build` not exiting correctly. It builds the application just fine, puts everything in the dist folder and it runs correctly if manually uploaded, but because the process hangs at `[vite-ssg] Build finished.`, Netlify considers it a failed build and doesn't actually serve the site.

~~[My Repo](https://github.com/Ragura)~~

Repeating the process on a fresh clone of the template does _not_ show this problem, meaning it would have something to do with my own project. But I have no idea how to start debugging this when the only message we get is "Build Finished". Also, aside from importing the Firebase development API, I have added no packages to the project, nor did I change any of the default template settings for Vite, WindiCSS or TS in any of the files.

I'm not expecting you to debug my project for me 😉But any hints as to where to possibly start looking would be very welcome!

**Comment by hannoeru** [comment]
Can you upgrade your dependencies then try again?

**Comment by Ragura** [comment]
Just did that (update latest even), still freezes without a proper exit.

**Comment by hannoeru** [comment]
Just take some time to dig into your code, is a async await problem.

https://github.com/Ragura/qrios-cinemax-evaluation/blob/1a88ab71090401629148143282467c92714b56c5/src/pages/users.vue#L35-L36
https://github.com/Ragura/qrios-cinemax-evaluation/blob/1a88ab71090401629148143282467c92714b56c5/src/pages/user.vue#L36-L38

You should use onMounted hook in these place, to avoid fetching data when building.

**Comment by hannoeru** [comment]
Also don't push your API key into github repo... is not save, you should delete the repo or set it to private.

**Comment by Ragura** [comment]
I had no idea it worked that way, first time working with SSG. Of course it makes sense when you think about the build process. I'll look into using onMounted(). **Thanks for the advice!**

The API key (Firebase config) was part of the repo because once deployed as a client app it would be exposed to the public anyway. Shouldn't be a security risk with Firebase.

**Comment by waelio** [comment]
@Ragura did you manage to solve your issue? I have the same issue

**Comment by Ragura** [comment]
@waelio Yes, I solved it by moving the functions that fetched data from Firebase to an onMounted hook. I believe the that’s because the async/await holds up part of the build process if it’s in the base setup function. It should only ever fetch when the page is accessed and the component is mounted, not when built.
