### ISSUE TITLE
Tailwind CSS IntelliSense  invalid

### ISSUE THREAD

**Issue by haliuhei** [antfu/vitesse#132]
vscode:1.56.2(system setup)
Tailwind CSS IntelliSense:0.6.6
Manually create the vite Vue project and install tailwindcss It's normal
`yarn create @vitejs/app`
reference documents(tailwindcss)
[https://www.tailwindcss.com/docs/guides/vue-3-vite](https://www.tailwindcss.com/docs/guides/vue-3-vite)
![image](https://user-images.githubusercontent.com/57513459/120741469-b2420680-c527-11eb-9f33-f2e67dd196f0.png)

but  use  'vitesse' project ,No CSS prompt
![image](https://user-images.githubusercontent.com/57513459/120741389-8cb4fd00-c527-11eb-9a54-c00e1d38cd4d.png)

**Comment by antfu** [comment]
We use Windi CSS: https://marketplace.visualstudio.com/items?itemName=voorjaar.windicss-intellisense

**Comment by haliuhei** [comment]
> We use Windi CSS: https://marketplace.visualstudio.com/items?itemName=voorjaar.windicss-intellisense

That's great. Thank you
