### ISSUE TITLE
vue shim declaration file missing?

### ISSUE THREAD

**Issue by jacobclevenger** [antfu/vitesse#14]
It seems the `vue-shims.d.ts` is missing from this project. I cloned the repo using `npx degit antfu/vitesse my-vitesse-app` and opened up the project in a fresh vscode install with only the recommended extensions installed just to make sure it wasn't a problem with my VSCode install. I assume a shims file is needed for typescript to recognize `.vue` extensions

![image](https://user-images.githubusercontent.com/7064956/93506997-0dc15b00-f8eb-11ea-959f-24a50750c5f5.png)

**Comment by antfu** [comment]
The shims are now auto-generated by `@vuedx/typescript-plugin-vue` with more accurate typing for each component

Can you try to install your deps and restart VS Code to see if it works?

https://github.com/antfu/vitesse/blob/aaedb2f9f1529688c7fb11fb12f912ffbd7ee5b4/tsconfig.json#L14

**Comment by jacobclevenger** [comment]
Hmm, no luck. I ran `pnpm i` and then restarted VS Code but still have the same error.

**Comment by jacobclevenger** [comment]
I should also note that I have tried this on both WSL(Ubuntu) and MacOS and get the same result for both.

**Comment by antfu** [comment]
Can confirm. Though I am not sure where the problem is. Adding back the shim as a workaround for now. Thanks a lot for helping to investigate.
