### ISSUE TITLE
[Question] How to change output routes in build mode?

### ISSUE THREAD

**Issue by mioe** [antfu/vitesse#143]
Hi I'm wondering if it is possible to change the architecture of folders and files?

now:
<img width="618" alt="изображение" src="https://user-images.githubusercontent.com/16230771/123593892-b1835400-d7f7-11eb-98ab-45ebce41cfea.png">

i try to do so:
```
dist/index.html
dist/readme/index.html
dist/about/index.html
```

**Comment by antfu** [comment]
Just organize them in the `pages/`
