### ISSUE TITLE
[Question] - Get frontmatter attributes  from md pages

### ISSUE THREAD

**Issue by alvarosaburido** [antfu/vitesse#144]
Is it possible to fetch the frontmatter attributes from pages done in `.md`  ? 

## Use case
List characters info in a `characters/index.vue` 

```
pages/
├─ characters/
│  ├─ mario.md
│  ├─ fox
│  ├─ link.md
```

```
// link.md

---
name: 'Link' 
img: '../link.png'
---

Blah blah blah
```

To get something like: 

```javascript
const characters = [ { name: 'Mario', img: '..' }, { name: 'Link', img: '..' } ... ]
```

**Comment by antfu** [comment]
https://github.com/antfu/antfu.me/blob/cd6b62b837dafc73fa773f7cf114f3c8532067b3/vite.config.ts#L58-L60
