### ISSUE TITLE
Static generated pages not rendering correctly

### ISSUE THREAD

**Issue by gitjeff05** [antfu/vitesse#148]
When running `pnpm build` inside of the vitesse starter, I see that vite-ssg is rendering static pages to dist:

```
[vite-ssg] Rendering Pages... (3)
dist/about.html  9.27kb
dist/index.html  8.19kb
dist/readme.html 7.83kb
```

However, when running `pnpm preview` and going to `http://localhost:5000/about.html` I get routed to the 404 page.

The `/about` route renders just fine, but none of the generated `{route}.html` files will render. I see a flash of the expected content and then that content disappears. 

I attempted to track it down (setting `build: { minify: false }` in `vite.config.ts`) and all I can tell is that it happens after vite-ssg calls [`app.mount(rootContainer, true)`](https://github.com/antfu/vite-ssg/blob/main/src/client/index.ts#L92). Stepping into the call to `app.mount` I can see that `container.innerHTML = ""` is called and then the content disappears.

My apologies if this belongs in [antfu/vite-ssg](https://github.com/antfu/vite-ssg). Let me know if you need more details. Thanks for the awesome work on vitesse!

**Comment by antfu** [comment]
You will need to access `http://localhost:5000/about` as `vue-router` only resolve to it.
