### ISSUE TITLE
Hot reloading not working on components folder

### ISSUE THREAD

**Issue by kmilogp8496** [antfu/vitesse#149]
PLEASE READ: I originally made this template for myself to mocking up apps quicker. I am glad to see you are willing to give it a try! Before your open the issue, please make sure you are reporting bugs in the template itself. **I am NOT creating this template to solve the problems you faced in your project, please use Vue or Vite's discord server to ask questions.** Thank you.

**Describe the bug/issue**

Hi, I just cloned the repo using 

npx degit antfu/vitesse my-vitesse-app

But I don't have hot reloading on my components folder.

Steps:

1- Clone the repo
2- Install node modules using "pnpm i"
3- In Footer.vue component add any class, e.g. "bg-red-600"

I don't know if this is intentioned, but if it is the case, please let me know. 

Thanks for your wonderful work.

**Comment by kmilogp8496** [comment]
It seems to be an issue with vite-plugin-components.

I tried with a new vite project, and when I add vite plugin components, and none of my files in my components folder gets reloaded

**Comment by hannoeru** [comment]
Are you using windows?

**Comment by robheymann** [comment]
Hi, I am experiencing the same issue. On windows

**Comment by kmilogp8496** [comment]
Yes, I am using window, I solved this downgrading vite-plugin-components to version 0.11.0, it seems to be an issue on version 0.12.0

https://github.com/antfu/vite-plugin-components/issues/86
