### ISSUE TITLE
[Question] - Any way to keep my vitesse-based code up-to-date with your changes?

### ISSUE THREAD

**Issue by armenr** [antfu/vitesse#153]
First, let me say: I love this boilerplate repo. It's probably one of the best I've ever used, ever, but also the best I've found for a "modern" vue3 stack with GOOD opinionation.

My one question is: Is it possible for me to structure or set up my repo in such a way, where I can continuously pull down any changes or improvements made here in the template into my repo?

If not, totally cool...just trying to think through this and see if there's a way. :)

**Comment by ivanq3w** [comment]
I was thinking about the same :) #147 
Maybe the easiest way is to manually merge vitesse template, and subscribe to updates.

**Comment by antfu** [comment]
Most of the updates to it are dependencies bumps, in that case you don't need to keep sync with the main repo. For occasional features updates (most of them are simple small changes), you could see them in commits and pick to your repo if you like them. - I don't really think you have to keep up to date with vitesse as it's just a template. If you really want, I guess there might be some tool for that, but I don't have opinion on them.

Thanks and glad you like it :)

**Comment by armenr** [comment]
Thank you @antfu. Just signed up to be a monthly supporter. Keep up the excellent work! :)
