### ISSUE TITLE
[Question] - [...all].vue

### ISSUE THREAD

**Issue by armenr** [antfu/vitesse#154]
I am uncertain as to how or why this file is named [...all].vue, and how it fits in with the rest of the code architecture. I'm guessing there's a very specific and intentional reason for this, but I'm just curious to understand what's behind the reasoning for naming a component `[...all].vue` or even `[name].vue`

Thank you again for ALL of your hard work! The closer I look at this project, more I want to jump in and help contribute/maintain it. I guess I just need to ask some questions - if there's a better way to get in touch, please do let me know and I'll stop nagging you via GitHub issues! :)

**Comment by ctholho** [comment]
This is indeed not the right repo for this question. 🙂

It's a feature of [vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages). And there you can also disable square brackets with the *experimental* option: `replaceSquareBrackets`.

At this repo you can find [this issue](https://github.com/hannoeru/vite-plugin-pages/issues/16) which links to nuxt, which might be the answer to your specific question.

If this answers your question or points you in the right direction, please close this issue.

**Comment by armenr** [comment]
Understood. Thank you! Appreciate you pointing me in the right direction. Thanks again @ctholho, and thanks @antfu for all of the insanely valuable and innovate work you're doing in this ecosystem!
