### ISSUE TITLE
postcss.plugin was deprecated

### ISSUE THREAD

**Issue by jewe11er** [antfu/vitesse#16]
Get alert on dev mode
postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
Used last version on 28.11.2020

**Comment by antfu** [comment]
PostCSS 7 plugins are compatible with version 8. It's just a deprecated warning but things would just work. Would need to wait until those plugins and `@vue/compiler-sfc` update in order the dismiss the warning. See more on https://github.com/vitejs/vite/pull/873#issuecomment-730155021
