### ISSUE TITLE
Backend server

### ISSUE THREAD

**Issue by folamy** [antfu/vitesse#160]
@antfu, well done, and thank you for this starter. 

This might sound odd but can I use a backend framework with this starter?
I mean something like a node-Server e. g Connect or expressJS?

**Comment by antfu** [comment]
https://vitejs.dev/guide/backend-integration.html#backend-integration

**Comment by userquin** [comment]
@folamy beware using `manifest: true` since it will fail on build, if you need generate client `manifest`, use `manifest: !process.env.VITE_SSG`
