### ISSUE TITLE
Validation error of functions

### ISSUE THREAD

**Issue by MatteoGauthier** [antfu/vitesse#164]
![image](https://user-images.githubusercontent.com/32040951/128263805-8e120f1d-ec65-4035-b73c-79e967a7cdd4.png)
Hey !! Firstly thanks for this blazing fast template !

I faced some validation error when if create function inside `<script setup>`

How can i hide those error ?

**Comment by antfu** [comment]
Use [Volar](https://github.com/johnsoncodehk/volar#using) instead of Vetur.

**Comment by MatteoGauthier** [comment]
> Use [Volar](https://github.com/johnsoncodehk/volar#using) instead of Vetur.

Okay thanks !
