### ISSUE TITLE
Can't iterate over yaml array of strings 

### ISSUE THREAD

**Issue by aidar-kz** [antfu/vitesse#165]
I have an array of strings in en.yml file like this:
```js
strings:
  - String 1
  - String 2
  - String 3
```
And I'm trying to display the array in a component using `v-for`:
`<li v-for="string in t('strings')">{{ string }}</li>`

But instead of displaying the array elements it iterates over the key and displays:
s
t
r
i
n
g
s

### Expected behavior

`v-for="$t('arrayOfString')"` iterates over array of strings, not over the key

### System Info

```shell
"vue": "^3.1.5"
"vue-i18n": "^9.1.7"
"vite": "^2.4.2"
```

### Screenshot
![image](https://user-images.githubusercontent.com/78292999/128372463-36edaceb-360d-4927-9ad2-07ef471296bc.png)

<img width="768" alt="Screen Shot 2021-08-05 at 8 47 28 PM" src="https://user-images.githubusercontent.com/78292999/128370582-4bb781fa-419b-4770-b98f-dcacd0e03f54.png">

![image](https://user-images.githubusercontent.com/78292999/128371768-3f3d42b0-4a4e-4679-a667-50edb6d6ee56.png)

**Comment by aidar-kz** [comment]
Excuse me, but why you closed this issue? Did I describe it not correctly? I'm using the Vitesse template and could not make it display yaml arrays, and could not find any solution googling, that's why posted here. If I did something wrong, I apologize, just thought you know your template and would be able to help me with this issue. Thank you.

**Comment by antfu** [comment]
https://github.com/antfu/vitesse/blob/main/.github/ISSUE_TEMPLATE/general.md

**Comment by aidar-kz** [comment]
Ah, I understand, of course, though it doesn't exclude the case when someone else could help. Anyway, I already found a solution. And thank you for a good template!

**Comment by antfu** [comment]
Hey man, I got hundreds of issues coming everday, issue temple is the only thing we can have to potentially reduce the amount of them and keep critical issues more appearable to maintainers' attention. As I said in the issue template, I don't have time and energy to deal with the issues coming from users variations. Please don't ignore it next time. Meanwhile, issue tracker is not the proper way to asking for help, there are GitHub discussions, Discord, Stackoverflow and forums for that.

Anyway, I am glad to hear you have find the solution for your issue.

**Comment by aidar-kz** [comment]
Sure man, will keep in mind what you said if any issues next time. Thanks again for your template, I really like it.
