### ISSUE TITLE
Full page reload

### ISSUE THREAD

**Issue by folamy** [antfu/vitesse#176]
I discovered there is always a full page reload when I edit any  file in the pages directory. 
Is this a bug or an intended behavior for viteSSG?

**Comment by userquin** [comment]
it comes from `vite-plugin-pages`: https://github.com/hannoeru/vite-plugin-pages/blob/6096a331ba5bd60283da28f0cb20e50d1e2125b5/src/index.ts#L49

**Comment by folamy** [comment]
Oh, I see!

**Comment by userquin** [comment]
@folamy previous link is wrong (just search hmr closed issue 55 on `vite-plugin-pages), the source line is this: https://github.com/hannoeru/vite-plugin-pages/blob/main/src/hmr.ts#L34

**Comment by folamy** [comment]
> @folamy previous link is wrong (just search hmr closed issue 55 on `vite-plugin-pages`), the source line is this: https://github.com/hannoeru/vite-plugin-pages/blob/main/src/hmr.ts#L34

Thanks! 
I got it already, it says to use v0.12.1
