### ISSUE TITLE
The project has a syntax error in VSCode

### ISSUE THREAD

**Issue by LittleSound** [antfu/vitesse#184]
## English (Deep translation)：
After creating a project with `npx degit antfu/vitesse my-vitesse-app` and installing all the VSCode dependencies described in README.md, VSCode prompts the error.

![image](https://user-images.githubusercontent.com/19204772/132195478-d8aec935-fc18-4767-b64a-145c87e162a2.png)

1. The module ". /App.vue" or its corresponding type declaration. 2.
2. The attribute "savedName" does not exist on the type "never".

I solved the first error by adding a .d.ts file of my own.
```typescript
declare module '*.vue' {
  import { defineComponent } from 'vue'
  const Component: ReturnType<typeof defineComponent>
  export default Component
}
```
But the second error is still there, and although it doesn't affect the operation, I'm having a hard time looking at it, how do I get rid of these errors?

## Original Chinese:
使用 `npx degit antfu/vitesse my-vitesse-app` 创建项目并且安装 README.md 中所描述的所有 VSCode 依赖之后，VSCode 提示错误：
![image](https://user-images.githubusercontent.com/19204772/132195478-d8aec935-fc18-4767-b64a-145c87e162a2.png)
1. 找不到模块“./App.vue”或其相应的类型声明。
2. 类型“never”上不存在属性“savedName”。

我通过自行添加一个 .d.ts 文件解决了第一个错误：
```typescript
declare module '*.vue' {
  import { defineComponent } from 'vue'
  const Component: ReturnType<typeof defineComponent>
  export default Component
}
```
但是第二个错误仍然存在，虽然这不影响运行，但是我看着很难受，如何消除这些错误？

**Comment by johnsoncodehk** [comment]
The first problem, you need to enable TS plugin by commmand `Volar: Switch TS plugin on / off`.

I can't reproduce the second problem, is it random? It looks like it is related to HMR. Is there a way to always reproduce?

**Comment by LittleSound** [comment]
I'll try the switch you mentioned.

If you're not getting the second error in vitesse, then I think it might also have something to do with the plugin settings in VS Code?

**Comment by LittleSound** [comment]
@johnsoncodehk
Regarding the first issue, I encountered an error when trying to turn on the TS plugin switch and it failed to execute.
![image](https://user-images.githubusercontent.com/19204772/132227473-d9063f4d-7e59-4c41-acd2-b7fbbd027387.png)


Regarding the second issue, I didn't reproduce it on my home computer, VS Code prompted me to update the vue-tsc version because my local version didn't match the version supported by the plugin, then I updated it, and the second error didn't reproduce on this updated vue-tsc computer, so I suspect it has something to do with that. I will try to update vue-tsc on my company computer tomorrow after I go to work, hopefully this will solve the problem.

Translated with www.DeepL.com/Translator (free version)

**Comment by LittleSound** [comment]
Never mind, after I tried several times of restarting VS Code to try to update it self, the `Volar: Switch TS Plugin on/off` command suddenly appears to be working right now, maybe caches or lags caused this issue somehow.

**Comment by johnsoncodehk** [comment]
> @johnsoncodehk
> Regarding the first issue, I encountered an error when trying to turn on the TS plugin switch and it failed to execute.
> ![image](https://user-images.githubusercontent.com/19204772/132227473-d9063f4d-7e59-4c41-acd2-b7fbbd027387.png)
> 
> Regarding the second issue, I didn't reproduce it on my home computer, VS Code prompted me to update the vue-tsc version because my local version didn't match the version supported by the plugin, then I updated it, and the second error didn't reproduce on this updated vue-tsc computer, so I suspect it has something to do with that. I will try to update vue-tsc on my company computer tomorrow after I go to work, hopefully this will solve the problem.
> 
> Translated with [www.DeepL.com/Translator](http://www.DeepL.com/Translator) (free version)

You need to open any vue file to trigger volar active first.

**Comment by LittleSound** [comment]
> > @johnsoncodehk
> > Regarding the first issue, I encountered an error when trying to turn on the TS plugin switch and it failed to execute.
> > ![image](https://user-images.githubusercontent.com/19204772/132227473-d9063f4d-7e59-4c41-acd2-b7fbbd027387.png)
> > Regarding the second issue, I didn't reproduce it on my home computer, VS Code prompted me to update the vue-tsc version because my local version didn't match the version supported by the plugin, then I updated it, and the second error didn't reproduce on this updated vue-tsc computer, so I suspect it has something to do with that. I will try to update vue-tsc on my company computer tomorrow after I go to work, hopefully this will solve the problem.
> > Translated with [www.DeepL.com/Translator](http://www.DeepL.com/Translator) (free version)
> 
> After reload vscode, you need to open any vue file to trigger volar active first.

In fact, it was a vue file behind the error prompt in the screenshot I posted above.

**Comment by LittleSound** [comment]
So let me summarize the solution to this problem.
1. Update your VS Code to make sure the version is up to date. The version I was using was a month old and did not work properly with all the plugins needed to run the project
2. Use the command line `pnpm up -latest vue-tsc` to update your vue-tac
3. open `Volar: Switch TS plugin on / off` in VS Code

After I did the above, both errors were solved without any problems.

**Comment by LittleSound** [comment]
Put it away for a while. Now it's loading a second error, why is that? It was fine just now, I haven't touched anything. This is so strange ......
![image](https://user-images.githubusercontent.com/19204772/132282967-fe599aa1-0296-4755-a7b6-6c6aad1d756a.png)

**Comment by johnsoncodehk** [comment]
@LittleSound Can this problem reproduce if you reload VSCode? if yes can you zip and provide the whole project (include node_modules)?

**Comment by LittleSound** [comment]
Reloading and reopening the program didn't work, I tried that.
I compressed my project, but its dependency files are too big and exceed the upload limit
I uploaded it using Google Drive:
https://drive.google.com/file/d/13KpNtzA2K4bqVQWQYZ7_wtNB54IEzw7Y/view?usp=sharing

**Comment by LittleSound** [comment]
> @LittleSound have tried updating Pinia to the latest version? I had that same error, but fixed after updating Pinia to latest version

This method is useful, thank you very much!
@antfu Does this mean Vitesse needs to update the "Pinia" version?
