### ISSUE TITLE
vite-plugin-pages : Build error

### ISSUE THREAD

**Issue by arlejeun** [antfu/vitesse#197]
Hi @antfu,
I'm trying to run this template out of box but I got this weird issue after running these commands. 

![image](https://user-images.githubusercontent.com/4977163/133716845-b664f435-98b3-4aa2-b01a-652f105d10c2.png)

Installation works just fine

But I can't run the application

![image](https://user-images.githubusercontent.com/4977163/133716904-b52cfaac-0d98-46de-a744-a2a948b8abe1.png)

 Can you please advise?

**Comment by antfu** [comment]
Works fine on my side, try upgrade to latest pnpm?

**Comment by arlejeun** [comment]
Thanks for the quick response and confirmation it works on your side!

Unfortunately, I had this issue with the latest version.
(base) alejeune@genesys my-vitesse-app $ pnpm -v
6.15.1

It should come from my environment. I don't want to waste your time. I will update the issue if I found a solution
Thanks for the cool stuff you're building.

**Comment by hannoeru** [comment]
try vite-plugin-pages v0.18.1

**Comment by arlejeun** [comment]
It works! Thanks guys for your quick response. You rock!
