### ISSUE TITLE
[Suggestion] Whether to add commitlint

### ISSUE THREAD

**Issue by YunYouJun** [antfu/vitesse#200]
I found that vitesse's commit basically follows the [Angular Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0-beta.4/) specification.

For example, `fix: xxx` `chore: xxx`.

Do we need add [commitlint](https://github.com/conventional-changelog/commitlint) for it?

If you think it's ok, i can create a PR for it.
If it is unnecessary, just close it.

**Comment by nandi95** [comment]
I think not.
There is no changelog generation and this is a template repo so not everyone will be using standardised commits.

**Comment by antfu** [comment]
I don't think it's neccessary. Thanks.
