### ISSUE TITLE
Why TailwindCSS and postcss-preset-env are not included?

### ISSUE THREAD

**Issue by kidsnjoy** [antfu/vitesse#206]
https://github.com/csstools/postcss-preset-env
https://tailwindcss.com/docs/installation

```
module.exports = {
  plugins: {
    tailwindcss: {},
    'postcss-preset-env': {
      stage: 3,
      features: {
        'nesting-rules': true
      }
    },
    autoprefixer: {},
  },
}
```

Or some better alternative has already been included in this template?

**Comment by antfu** [comment]
We use Windi CSS which does not relay on postcss.
