### ISSUE TITLE
What are the replacement for axios and vuex in vitesse?

### ISSUE THREAD

**Issue by cyfung1031** [antfu/vitesse#209]
Hi 

I think axios and vuex are both popular vue plugins for vue 2 & 3, but I do not found them in vitesse.
Any good replacement for them?
`useFetch` in vueuse?

Any reason/benefit for not using axios and vuex??? 

Thank you.

**Comment by userquin** [comment]
I think there is no explicit network requests on vitesse. Anyway, you can use `useFetch` from `@vueuse`  since axios os blocking.

About vuex, there is not yet an stable version to use it woth vue3, we use pinia instead.

**Comment by userquin** [comment]
You can also use `useAxios` from `vueuse`.

**Comment by antfu** [comment]
> Any reason/benefit for not using axios and vuex???

This is just a template. Add them are you want.

**Comment by cyfung1031** [comment]
I found that the replacement for vuex is pinia in this template.
