### ISSUE TITLE
is there a reason why why markdown it basic css isn't working ?

### ISSUE THREAD

**Issue by AmrBashir** [antfu/vitesse#21]
Without the spacing provided by this css for `<p>` tags, new lines are not correctly rendered.
https://github.com/antfu/vitesse/blob/bcfa93e1d4e3345961b7d5be58047b30388665cb/src/main.postcss#L18-L34
Also `# h1` doesn't render correctly.

using `vite-plugin-md` in a new bare-bone vite project seems to work fine though.

**Comment by AmrBashir** [comment]
I guess I am onto something; resetting css margins and paddings like this
```css
* {
	margin: 0,
	padding: 0,
}
``` 
does indeed remove the spacing of the markdown css but still doesn't quite explain why something like this `# H1` doesn't work.

I am not a tailwind user so I am not sure if there css has some sort of resetting.

**Comment by antfu** [comment]
Tailwind will reset them (including h1, h2, etc.) to the plain text. I guess maybe I should include https://github.com/tailwindlabs/tailwindcss-typography in Vitesse so they can have reasonable styling.

**Comment by AmrBashir** [comment]
Yeah, I think that would be good, or a simple note in README.md would do it.

**Comment by antfu** [comment]
@AmrBashir Forget to mention, it's already included in the latest version

**Comment by AmrBashir** [comment]
thanks for letting me know.

**Comment by AmrBashir** [comment]
Thanks ❤
