### ISSUE TITLE
Character encoding error

### ISSUE THREAD

**Issue by HydraCOREY** [antfu/vitesse#210]
Running the demo app, I get the following error:
`The character encoding of the plain text document was not declared.`

Ran the following to get this error:
```bash
npx degit antfu/vitesse vitesse-app
cd vitesse-app
pnpm i
pnpm dev
```

Image of error and view of app:
![image](https://user-images.githubusercontent.com/15674865/136278141-d9a76152-a9fc-4471-9e09-65bbfaca2ffd.png)

**Comment by CoreyVincent** [comment]
Some more info:
pnpm - 6.16.1
node - v14.15.4
vscode - 1.60.2
firefox - 92.0.1

**Comment by userquin** [comment]
I think you need to import `useAxios`  on your `index.vue`, since there is no preset yet for `@vueuse/integrations`. I haven't control the `@vueuse` on the `auto import` plugin so it seems it is missing or you must include the preset (I only see it only includes the core and head).

**Comment by CoreyVincent** [comment]
@userquin 
Downgraded vite (2.6.7) and windicss (1.4.9).
I'm using Windows 10 (19043.1288) with WSL2 (Ubuntu 20.04.3 LTS)
