### ISSUE TITLE
I encountered a lot of "react/*" errors when using "JSX/TSX".

### ISSUE THREAD

**Issue by LittleSound** [antfu/vitesse#215]
I'm getting a lot of react errors when using JSX.
![image](https://user-images.githubusercontent.com/19204772/137883085-054b5236-da09-4699-9d87-cdb0e3344a4e.png)

And the .eslintrc in your project relies on [@antfu/eslint-config](https://www.npmjs.com/package/@antfu/eslint-config).
[@antfu/eslint-config](https://www.npmjs.com/package/@antfu/eslint-config) contains [@antfu/eslint-config-react](https://www.npmjs.com/package/@antfu/eslint-config-react), which seems to be the reason for these errors, but this is a vite + vue project, which shouldn't contain react configuration.

How do I turn off "React" syntax detection for "ESLint"?

**Comment by LittleSound** [comment]
> https://github.com/antfu/eslint-config

@antfu 
I was hoping I could get some help on how to remove `@antfu/eslint-config-react` from this project. I have no experience in this area. 🙏 Thank you

**Comment by zcyc** [comment]
@LittleSound hi, do you fix this issue? i cant fix it .

**Comment by LittleSound** [comment]
> @LittleSound嗨，你解决了这个问题吗？我无法修复它。

I haven't found a good way, so every time I encounter this kind of error, I go to the configuration file to turn off the corresponding check rules separately
