### ISSUE TITLE
[Question] How do you can code this template?

### ISSUE THREAD

**Issue by harrytran998** [antfu/vitesse#23]
Today, I open this template(lastest of repo) --> But have issue with VSCode.
1. Module have no default export
2. In template, have no suggestion code.
![image](https://user-images.githubusercontent.com/24296018/102641264-5c9ebb00-418e-11eb-9dd2-b6086494feab.png)

I researched and found this https://github.com/vuejs/vitepress/pull/137#issuecomment-733868635 --> Evan suggest use Volar, then I try but still not work! I use **Vetur 0.31.3** and VsCode **lastest**. 

Hope you can answer this question :v

**Comment by antfu** [comment]
I am using Vetur and somehow I don't see the error on my side. But frankly, Vitesse uses a lot of experimental features (include Vite which doesn't have a stable release yet). Which you would potentially face breaking changes and incomplete editor support. I would recommend to hold it for a while if you really care about them.

**Comment by harrytran998** [comment]
Thank you for your quick response! I will try, because this is awesome 🥳! I appreciate your works!

**Comment by antfu** [comment]
You may like to have this config
```json
"vetur.validation.interpolation": false,
```

**Comment by harrytran998** [comment]
This config fixed problem no default export 🥳, but still don't have code suggestion :v

**Comment by ksnyde** [comment]
I believe this "no default export" error is a result of using the still experimental `<script setup>` RFC. If you use the composition api in the standard way this error will go away. That said, this error in the template, is a visual inconvenience but doesn't actually prevent TS from transpiling.

**Comment by ksnyde** [comment]
Also be aware of Vetur's `globalComponents` property. The default setting for it is `[]` and that is worth sticking to with Vitesse because Vitesse actually registers all components for you and this setting is just meant to "autocomplete" component names within a glob pattern. So setting this actually causes interference. If this last post made no sense then ignore it. :)

**Comment by antfu** [comment]
I have switched to Volar for this project which has great support for `<script setup>`, closing this for now.
