### ISSUE TITLE
[QUESTION] - Can't move html files to other folder

### ISSUE THREAD

**Issue by sujit-baniya** [antfu/vitesse#234]
Hi,

Thank you for your library. I build the assets and tried to copy html files to different folders and use the assets from those html files. But it shows all blank. Just within a millisecond the designs are visible but again it goes blank.

Please check this video: https://storyxpress.co/video/kw23fjnwm1n67wz5x

Please help fixing this issue

**Comment by userquin** [comment]
@sujit-baniya it seems you are using `/app/` context to serve your app, so you should change the `base` entry on `vite.config.ts`, configure also the router `base` entry on `router options` on the `main.ts`: https://vitejs.dev/config/#base

You can see how the router is configured here (`vite-ssg`): https://github.com/antfu/vite-ssg/blob/main/src/client/index.ts#L36

```ts
// vite.config.ts
export default defineConfig({
  base: '/app/`,
  resolve: {
  ...
}
```

```ts
// main.ts
// https://github.com/antfu/vite-ssg
export const createApp = ViteSSG(
  App,
  { routes,  base: '/app/` },
  (ctx) => {
    // install all modules under `modules/`
    Object.values(import.meta.globEager('./modules/*.ts')).map(i => i.install?.(ctx))
  },
)
```

**Comment by antfu** [comment]
This is just a template, you need to figure the problem of your custom configuration your own.
