### ISSUE TITLE
How to correctly deploy the application on a subdirectory? ("base" issue)

### ISSUE THREAD

**Issue by arbassic** [antfu/vitesse#242]
### Discussed in https://github.com/antfu/vitesse/discussions/226

<div type='discussions-op-text'>

<sup>Originally posted by **lhoucinecherif** October 30, 2021</sup>
Hi,
I cant' find a correct way to deploy the built app on a subdirectory on my prod server ! 
I've added the "base" param in the vite.config.ts file, but I got a not found page (catch all page) instead of the home page!!

Thanks</div>

Help will be appriciated! :)

**Comment by antfu** [comment]
Please use discussions.
