### ISSUE TITLE
how to implement router guard

### ISSUE THREAD

**Issue by michaelmok2021** [antfu/vitesse#244]
Thank you for creating this template. In regard to the auto route, how do I implement an router guard eg some pages are protected and requires authenticated access?

**Comment by antfu** [comment]
https://next.router.vuejs.org/guide/advanced/navigation-guards.html

**Comment by edshen17** [comment]
Here's how I was able to add navigation guards:

1) Make a module because you can access the router there
```
// in /src/modules/router.ts

import { type UserModule } from '~/types'

export const install: UserModule = ({ isClient, router }) => {
  if (isClient) {
    const userStore = useUserStore()
    const isLoggedIn = userStore.isLoggedIn
    router.beforeEach((to, from, next) => {
      const requiresAuth = to.meta.requiresAuth
      // your auth logic
    })
  }
}
```

2) Add metadata in your pages (eg: `/src/pages/dashboard.vue`)

```
<template>
  <div>dashboard</div>
</template>

<route lang="yaml">
meta:
  layout: default
  requiresAuth: true
</route>

```

Hope this helps!
