### ISSUE TITLE
Documentation: some icons cannot be used on offline mode

### ISSUE THREAD

**Issue by userquin** [antfu/vitesse#25]
Hi:

It would be great if we can include some guide on `vitesse` to include some icons that `vite-plugin-purge-icons` just delegates to a network call to `iconify` (because some dev dependencies are misssing), and then on offline mode just doesn't work.

For example, I have changed the icon for dark and night mode to use mdi icons (`mdi-brightness-6` to switch to dark mode and `mdi-brightness-4` to switch to light mode), and when I set the service worker on offline mode and switch from light to dark mode, then the icon dissapear and get an error from the network tab.

As a guide:
1) Add icon set and tools from `iconify` as dev dependencies: `pnpm install --save-dev @iconify/json-tools @iconify/json`
2) Modify `PurgeIcons` to include icons to your icon set, for exmaple:
```javascript
    PurgeIcons({
      // globs for searching source file to analyze
      content: [
        '**/*.html',
        '**/*.js',
        '**/*.vue', // scan for .vue file as well
      ],
      // whitelist for icons that might be used dynamically
      included: [
        'mdi:brightness-6', // from Material Design Icons
        'mdi:brightness-4', // from Material Design Icons
      ],
    }),
```

Bye.

**Comment by userquin** [comment]
Or maybe, just add these 2 dev dependencies to `vitesse template`.

**Comment by antfu** [comment]
With the latest Vitesse, I have switched to https://github.com/antfu/vite-plugin-icons and https://github.com/antfu/vite-ssg, which should solve your problem (but need some refactoring)
