### ISSUE TITLE
How to use I18N in TS file

### ISSUE THREAD

**Issue by admin8756** [antfu/vitesse#266]
I need a config file. To store some static properties. But I18N cannot be used inside.

I created a new config.ts

``` TypeScript
const { t } = useI18n();

/* 页面底部配置 */
export const FooterFunctionList = [
  {
    icon: 'home',
    name: t('footerList.home'),
    func: () => {},
  }
]
```
But when used this way. The project will report an error

Uncaught SyntaxError: Must be called at the top of a `setup` function

I think we should provide a method to use in the TS file. This is an excellent template. Adapt the functions that a large project should have.

**Comment by antfu** [comment]
IDK, check the docs of https://github.com/intlify/vue-i18n-next
