### ISSUE TITLE
Two route records for one real route

### ISSUE THREAD

**Issue by ShroXd** [antfu/vitesse#267]
## Overview

When I check the value of `useRouter().getRoutes()`, I found there are two record for one _real_ route. They are similar, but some fields have different values.

![image](https://user-images.githubusercontent.com/48713853/147932592-995b0931-0dfe-4fbd-9510-e8ba9d07ad63.png)

### Repetition step

1. Clone the _vitesse_
2. Open the src/pages/index.vue
3. Add following code:
```ts
// ...

const router = useRouter()
const go = () => {
  if (name.value)
    router.push(`/hi/${encodeURIComponent(name.value)}`)
}

// Add this line
console.log(router.getRoutes())

// ...
```
4. Run the project, check the console tab of browser

Thank you for any help!! ~I almost punch my screen~

**Comment by 8bu** [comment]
You should open an issue on https://github.com/hannoeru/vite-plugin-pages

**Comment by hannoeru** [comment]
https://github.com/JohnCampionJr/vite-plugin-vue-layouts/issues/47
