### ISSUE TITLE
Presite can't load CSS resource

### ISSUE THREAD

**Issue by ksnyde** [antfu/vitesse#27]
I am able to build using **Vite** without issue but attempting to prerender with Presite seems to fail with the following message:

```sh
Message from http://localhost:64987/_assets/style.af3afb7c.css:undefined:undefined Failed to load resource: net::ERR_FAILED
```

But the referenced file does exist (see below). That said, I have no idea why the `:undefined:undefined` is part of the node net::ERR_FAILED message.

![image](https://user-images.githubusercontent.com/980757/103264505-bc9c1b00-495f-11eb-8d68-c58420b2d588.png)

**Comment by ksnyde** [comment]
If I run **Presite** from the command line, I get the following output: 

```sh
Using config from presite.config.js
Copy static assets
Crawling contents from http://localhost:52860/
Message from http://localhost:52860/_assets/style.af3afb7c.css:undefined:undefined Failed to load resource: net::ERR_FAILED
Message from http://localhost:52860/_assets/index.8b2590b7.js:44:190465 Alumni app is mounted
Crawling contents from http://localhost:52860/profile
Writing /index.html for /
Message from http://localhost:52860/_assets/index.8b2590b7.js:44:190465 Alumni app is mounted
Writing /profile/index.html for /profile
Done, check out OUT folder
```

and looking at the two index files that are produced, i see the same link reference in the HTML:

```html
<link rel="stylesheet" href="/_assets/style.af3afb7c.css">
```
and interestingly it only errors on the root route. Seems very odd.

**Comment by ksnyde** [comment]
Indeed if I run a simple HTTP server on the output of Presite, I get no errors in the Chrome console:

![image](https://user-images.githubusercontent.com/980757/103265104-a7c08700-4961-11eb-8d94-abb6fa78fa42.png)

and from the server logs I can see the style sheet being loaded:

![image](https://user-images.githubusercontent.com/980757/103265166-ccb4fa00-4961-11eb-9817-d9dcc607ca84.png)

**Comment by ksnyde** [comment]
Should I be adding this to the Presite repo's issues?

**Comment by ksnyde** [comment]
For now I've commited a "the blind leading the naked" commit which changes the build to:

```json
{
  "build": "cross-env NODE_ENV=production vite build 2> /dev/null && esno scripts/ssg.ts 2> /dev/null"
}
```

Can't say I feel good about this but it does build successfully. It would appear that both the **postcss** warnings and the **presite** error write to STDERR and this then returns an error code to Node's process.

**Comment by ksnyde** [comment]
That you didn't experience this must be in part due to my running the build within the Rush monorepo's build command and it may be producing the error code when finding text in STDERR.

**Comment by antfu** [comment]
I have switched from Presite to https://github.com/antfu/vite-ssg in the latest Vitesse, which you may want to give a try. Unlike presite, it uses ssr from Vue core to render the content and should be more accurate on hydration and faster build.

And if you believe it's Presite's problem with your configured env, you can open an issue there.

**Comment by ksnyde** [comment]
Ok great. I'll give this a try and post this issue to presite. Also wanted to say thank you for all the amazing stuff you're contributing to open source. Loved this starter template and love all the TS stuff you're doing as well.
