### ISSUE TITLE
the layout system not work in tsx

### ISSUE THREAD

**Issue by zcyc** [antfu/vitesse#279]
```
export default defineComponent({
  setup() {
    return () => <>
      <route lang="yaml">
        meta:
        layout: home
      </route>
    </>
  },
})
```
it's always use default layout
![image](https://user-images.githubusercontent.com/9925064/150170853-6d608222-2b03-4a89-b53a-da21eb83f205.png)

**Comment by zcyc** [comment]
eslint rule is not work good for tsx yet

**Comment by antfu** [comment]
This is out-of-scope of Vitesse. Please request to `vite-plugin-vue-layout` instead.

**Comment by zcyc** [comment]
> It may also be that the yaml is invalid. Try indenting the layout definition.
> 
> ```
> <route lang="yaml">
>     meta:
>       layout: home
> </route>
> ```

改成规范 yaml 也不能用的。
