### ISSUE TITLE
Conflict if component name is same as page name

### ISSUE THREAD

**Issue by kissu** [antfu/vitesse#304]
I found out that I do have an infinite loop when having a page named `/test` and a `Test.vue` component

<img width="636" alt="image" src="https://user-images.githubusercontent.com/5133074/155105132-31db1a54-cc8c-4873-a59f-de7eac55e192.png">

I do also get those warnings, even if it's totally unrelated to attrs since I do not have any root nodes: https://github.com/akauppi/GroundLevel-firebase-es/issues/20

`/pages/index.vue`
```html
<template>
  <router-link :to="{ name: 'test' }">
    go to test page
  </router-link>
</template>
```

`/pages/test.vue`
```html
<template>
  <div>
    this is a test page, below test component
  </div>

  <test />
</template>
```

`Test.vue` component
```html
<template>
  this is a test component, cool huh?
</template>
```

This is using the latest version of Vitesse, and here is a [Github repo](https://github.com/kissu/vitesse-route-component-conflicts), trying to build it of course [crashes](https://app.netlify.com/sites/condescending-hypatia-cf229e/deploys/6214aec232204659ca42d4f8).

**Comment by antfu** [comment]
I think this is how Vue SFC has been defined. Try rename your component add avoid this usage.

**Comment by antfu** [comment]
https://github.com/vuejs/rfcs/blob/master/active-rfcs/0040-script-setup.md#automatic-name-inference

**Comment by kissu** [comment]
Yep, simply knowing this is enough. Just wanted to point it out, if somebody stumbles upon this!
