### ISSUE TITLE
CSS preprocessors - is it using postCSS 

### ISSUE THREAD

**Issue by demiro** [antfu/vitesse#307]
So not an issue, but would like to know how to use the preprocessors...

I reckon since it is using tailwind (and in my previous version windi) - it is using PostCSS out of the box?
I couldn't find any relation to it in package.json or vite config...

could you please let me know?
I am using @apply syntax and it seems to work, but @nest does not appear to work!

So I would like to install the @nest PostCSS plugin... how would I go about it?

Would appreciate any information about it

**Comment by antfu** [comment]
https://vitejs.dev/guide/features.html#postcss
