### ISSUE TITLE
vue-i18n esm bundler issue

### ISSUE THREAD

**Issue by shamscorner** [antfu/vitesse#311]
Is there any way to solve the following warning?

> You are running the esm-bundler build of vue-i18n. It is recommended to configure your bundler to explicitly replace feature flag globals with boolean literals to get proper tree-shaking in the final bundle. 

**Steps to reproduce:**
- Lunch the project
- Open browser dev-tool and see the console warning
- Make sure the console warning on your browser is enabled.

**Comment by userquin** [comment]
@shamscorner nopes, should be fixed upstream, the optimizations are configured, but on dev ignored.

You can check this issue, adding the esm alias should work: https://github.com/antfu/vitesse/issues/131

**Comment by shamscorner** [comment]
@userquin It worked! However, if it is a valid fix for this issue, why not add this into the repo then? Thanks for your help. I am closing this issue.
