### ISSUE TITLE
How do you create "middleware" concept in vite-plugin-pages with SSG? 

### ISSUE THREAD

**Issue by rezelute** [antfu/vitesse#317]
I really like the vitesse template and would love to use this in production however I'm a little confused by how to use Middleware in routes. For example, in Nuxt you can create a `middleware` folder and then specify things like: 
1- If the user is not logged in, go to the `HomeLoggedOut` page
2- I dont want this page to be included in the project based on the ENV file (allow_page_Hello_based_on_env_variable)

In the template, I am using vite-ssg which has the concept of `includedRoutes` however they will only happen at the build issue for example:
```
includedRoutes(paths, routes) {
   if(!env_has_feature_A){
      // filter out the page
   }
},
```
I can see that vite-plugin-pages has the concept of SFC custom block for Route Data which might solve the logged-in issue above (However im not sure how to implement this with SSG). And I dont know how to approach point 2 above (only include a page in the project if `allow_page_Hello_based_on_env_variable`. 

If you could please point me in the direction to solve both issues above, I would really appreciate it! Basically I just want more control over routes while using SSG.

**Comment by antfu** [comment]
Vitesse is just a light SPA template, SSG is more like addition for ppl want to do blogging of something with it. For more advanced usage I think you'd better use Nuxt directly.

**Comment by rezelute** [comment]
Hi Anthony, thank you for the direct reply :). Sorry but my question wasnt so much about SSG. It was asking about how I would setup a structure in pages for login and middleware so that I can exclude certain pages while developing.

**Comment by rezelute** [comment]
The problem im having is that https://github.com/hannoeru/vite-plugin-pages has some good configuration but i cant figure out how to use this configuration alongside SSG.
