### ISSUE TITLE
为啥会报Error 呀

### ISSUE THREAD

**Issue by Wang-zhetao** [antfu/vitesse#321]
PLEASE READ: I originally made this template for myself to mocking up apps quicker. I am glad to see you are willing to give it a try! Before your open the issue, please make sure you are reporting bugs in the template itself. **I am NOT creating this template to solve the problems you faced in your project, please use Vue or Vite's discord server to ask questions (or it might be closed directly without further notice).** Thank you.

**Describe the bug/issue**

我用npx 去安装时报了错
could not fetch remote https://github.com/antfu/vitesse
! could not find commit hash for HEAD

**Comment by Chenyuanyuan299** [comment]
> PLEASE READ: I originally made this template for myself to mocking up apps quicker. I am glad to see you are willing to give it a try! Before your open the issue, please make sure you are reporting bugs in the template itself. **I am NOT creating this template to solve the problems you faced in your project, please use Vue or Vite's discord server to ask questions (or it might be closed directly without further notice).** Thank you.
> 
> **Describe the bug/issue**
> 
> 我用npx 去安装时报了错 could not fetch remote https://github.com/antfu/vitesse ! could not find commit hash for HEAD

我也碰到了这个问题，所以是怎么解决的？
