### ISSUE TITLE
add email address use YAML cannot read properties?

### ISSUE THREAD

**Issue by leosin** [antfu/vitesse#324]
**Describe the bug/issue**

When using i18n, an error is reported if an email symbol is added to the yaml file.
Is this a problem with the i18n plugin?
```
mail: foo@bar.com
```
![image](https://user-images.githubusercontent.com/3676670/161338013-00669a65-e881-4c15-a648-4fce9fd5b2a8.png)

So for now I can only use # instead

**Comment by userquin** [comment]
You should escape it, check the vue-i18n docs, try first to enclose the email with single quotes
