### ISSUE TITLE
Add vuex support

### ISSUE THREAD

**Issue by Rolanddoda** [antfu/vitesse#33]
That's an awesome project I just discovered.

I'm trying to learn vue 3 by building some small apps and this template can be very helpful.

Is there any plan to add vuex 4 support and some small examples using it ? It would be great if there is some examples using vuex 4 modules.

**Comment by antfu** [comment]
I am not interested in add Vuex 4 to this template as the composition api can already take cover of most of the scenarios sharing and managing states. Will consider for Vuex 5 (which should be built on top of VCA) when it comes out.

But meanwhile, feel free to fork this template and add Vuex by yourself. If you find that also interesting to be as a template, I am happy to feature yours on the readme just like `vitesse-lite`.

Thanks.
