### ISSUE TITLE
unmet peer vue-i18n@next: found 9.1.9

### ISSUE THREAD

**Issue by Youdaman** [antfu/vitesse#335]
This is a similar issue to https://github.com/antfu/vue-starport/issues/34

That issue was not related to Starport, so I think this might be marked as not related to Vitesse, however it's the same issue with the same solution.

When I try to install Pug via `pnpm i -D pug` I get:
```
ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
└─┬ @intlify/vite-plugin-vue-i18n
  └── ✕ unmet peer vue-i18n@next: found 9.1.9
```

And the fix is the same as with the linked issue above, by doing `pnpm i -D @intlify/vite-plugin-vue-i18n@3.4.0` and then Pug will install successfully.

Sorry for any misunderstanding on my part, but is this issue and the one linked above to do with Vitesse or the i18n plugin for Vite?

I understand it's i18n causing the error but I've had it with two projects that use Vitesse (assuming Starport uses it) so I thought I'd mention it here in case another user of Vitesse encountered the same issue when trying to install modules.

**Comment by antfu** [comment]
You can safely ignore it. If you find it really annoying you can create an issue to `@intlify/vite-plugin-vue-i18n` instead.
