### ISSUE TITLE
[question] How to specify template on .md files in file routing

### ISSUE THREAD

**Issue by Codermar** [antfu/vitesse#340]
I am trying to use different templates for the md files used in file routing. i.e. the about.md file uses the default template.
My expectation would be that I could specify the template in the meta section of the md. file as in:

```
---
title: About
layout: myLayout
---
```
or 
```
---
title: About
meta:
  layout: bricks
---
```
I don't see this documented anywhere. Is it possible? How would I do this?
(My recommendation would be to add this to the out of the box example of about.md or document it somewhere)

Thanks

**Comment by Mert75** [comment]
@Codermar this is already possible - you can simply paste the following at the end of your markdown file:

```js
<route lang="yaml">
meta:
  layout: bricks
</route>
```

**Comment by Codermar** [comment]
Thank you!
