### ISSUE TITLE
@intlify/vite-plugin-vue-i18n warning

### ISSUE THREAD

**Issue by ArgekarStudios** [antfu/vitesse#343]
WARN  Issues with peer dependencies found
.
└─┬ @intlify/vite-plugin-vue-i18n
  └── ✕ unmet peer vue-i18n@next: found 9.1.10

**Comment by antfu** [comment]
You can ignore it for now. It's an upstream issue an there is nothing we can do.

**Comment by Youdaman** [comment]
Just out of interest, as I'm new to pnpm, do you mean adding something like this to package.json when you say "ignore"?
```
 "pnpm": {
    "peerDependencyRules": {
      "allowedVersions": {
        "vue-i18n": "9"
      }
    }
  }
```
