### ISSUE TITLE
favicon.svg dark mode doesn't seem to work

### ISSUE THREAD

**Issue by Lanseria** [antfu/vitesse#345]
> PLEASE READ: I originally made this template for myself to mocking up apps quicker. I am glad to see you are willing to give it a try! Before your open the issue, please make sure you are reporting bugs in the template itself. **I am NOT creating this template to solve the problems you faced in your project, please use Vue or Vite's discord server to ask questions (or it might be closed directly without further notice).** Thank you.

**Describe the bug/issue**
```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
  <style>
    path { fill: #222; }
    @media (prefers-color-scheme: dark) {
      path { fill: #ffffff; }
    }
  </style>
  <path d="M27.562 26L17.17 8.928l2.366-3.888L17.828 4L16 7.005L14.17 4l-1.708 1.04l2.366 3.888L4.438 26H2v2h28v-2zM16 10.85L25.22 26H17v-8h-2v8H6.78z" />
</svg>
```

like this

![image](https://user-images.githubusercontent.com/14802764/166625415-e5b46118-c967-493d-a764-ef82f10661f8.png)

**Comment by antfu** [comment]
Found that too. It works in previous Chrome, probably Chrome made some changes to it (or a regression). Leave it open if anyone have better solution to workaround it.
