### ISSUE TITLE
ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

### ISSUE THREAD

**Issue by ArgekarStudios** [antfu/vitesse#354]
pnpm issue after adding vite-plugin-inspector

**Comment by webfansplz** [comment]
![image](https://user-images.githubusercontent.com/22515951/167526688-8f11175e-afb2-4448-8e8f-ca9cdf4cff26.png)

There seems to no be related with adding it, be related to #343

**Comment by hannoeru** [comment]
Can't reproduce this issue in main branch, close for now. you can reopen it if this happen again.
