### ISSUE TITLE
Remove unoCSS until it is stable

### ISSUE THREAD

**Issue by Valentin-Seehausen** [antfu/vitesse#355]
Hey, I love Vitesse, and I like unoCSS.

I think unoCSS should be removed from Vitesse, until downward compatibility is ensured. Or better: When the engine is included in WindiCSS.

It takes a lot of time to make things work, there are error messages that are complicated to understand, and some classes just don't work (lg:hidden).

In general, the developer experience of Vitesse is super great and I think it should not be hurt by unoCSS. :-)

**Comment by antfu** [comment]
UnoCSS is stable. And this is a just template after all, feel free to alter the stack as you want.

**Comment by Valentin-Seehausen** [comment]
Hey, @antfu I have to admit, I found the error on my side ... Sorry :-)
