### ISSUE TITLE
Where is vue router created?

### ISSUE THREAD

**Issue by RovshenTagangylyjov** [antfu/vitesse#356]
I want to implement [vue-router-prefetch](https://github.com/egoist/vue-router-prefetch) and add some navigation guards. But i don't know how to do it since router is auto generated and i don't know where it is.
**Note: vue-router-prefetch has to be used after creating router.**

**Comment by hannoeru** [comment]
Vue router is created inside vite-ssg, you can access app and router instance using modules.

FYI: https://github.com/antfu/vitesse/tree/main/src/modules

**Comment by RovshenTagangylyjov** [comment]
Thanks @hannoeru

**Comment by RovshenTagangylyjov** [comment]
@hannoeru  [vue-router-prefetch]( https://github.com/egoist/vue-router-prefetch:) has to be registered after vue router. And when i try to use vue-rotuer-prefetch on modules it says:
```
[vue-router-prefetch] You need to call Vue.use(VueRouter) before this plugin!
```

I think that's because vite-ssg creates router after installing all modules. But i need to register prefetch module after creating router.

What can i do, do you have any ideas?
