### ISSUE TITLE
multi language for markdown example

### ISSUE THREAD

**Issue by sadeghbarati** [antfu/vitesse#36]
Thanks for Vitessg <3

**Comment by antfu** [comment]
Not sure if this should be a case tho. Markdown for me is content like a blog post or something that you would not do i18n for it normally. Instead, you are more likely to have two posts in different languages. The markdowns in Vitesse are just a showcase of what you can do with it but not a fully functional and i18n-ready app. So, I might not consider this for now. Thanks.
