### ISSUE TITLE
Add an example of how to include an image as an asset

### ISSUE THREAD

**Issue by Valentin-Seehausen** [antfu/vitesse#367]
Hey,

I actually have a hard time adding an image as a CSS background and deploying it to a static site.

What do you think about adding an example for a) an inline image and b) a CSS background image?

**Comment by antfu** [comment]
Please read Vite's docs, thanks

**Comment by Valentin-Seehausen** [comment]
I get this, but why not add an image to the repo? You have examples for routes, stores, pwa symbol, etc.
