### ISSUE TITLE
Component type checking does not work out of box

### ISSUE THREAD

**Issue by Bobakanoosh** [antfu/vitesse#373]
**Describe the bug/issue**

After fresh cloning this template, the type checking for components does not work.

**To reproduce:**
1. Clone project
2. Install using `pnpm`
3. Use `Typescript Vue Plugin (Volar)` and `Vue Language Features (Volar)`
4. Add ` <Counter :initial="{ a: 5 }" />` to `App.vue`

`Counter.vue` has a prop `initial` of type `number`. Here I am passing an object, `{ a: 5}`, but do not get any warning from the editor.

![image](https://user-images.githubusercontent.com/10647192/173389875-db0c7aeb-e3a6-4af9-85f9-08c188beec46.png)
As seen in the above image, the editor still recognizes the types of the component.

I'm making this issue in this template because if I create a fresh vue project via `pnpm create vue@latest`, the type checking works.

**Comment by antfu** [comment]
As https://github.com/johnsoncodehk/volar/issues/1077#issuecomment-1146584565 you can now remove `html.d.ts` safely.
