### ISSUE TITLE
Incorrect grammatical use

### ISSUE THREAD

**Issue by rudrakshkarpe** [antfu/vitesse#388]
###  In ``` READMD.md``` under ```why``` section 

- On line no. 4,  it is written as ``` or even maintains``` where it should be ``` or even maintain ``` considering the best grammatical practices.
- I hope this will make ```vitesse``` more precise to the users.

**Comment by antfu** [comment]
PR welcome

**Comment by rudrakshkarpe** [comment]
### Thanks for allowing me to make a PR, looking forward to contributing ahead :)
