### ISSUE TITLE
Some internal link failed to be rendered

### ISSUE THREAD

**Issue by ansidev** [antfu/vitesse#402]
### Describe the bug

I used a script to build the RSS link based on https://github.com/vuejs/blog/blob/master/.vitepress/genFeed.js

The production link is https://ansidev.xyz/feed.rss.

This link cannot be rendered properly if I click on the RSS link on the header bar, the response message is 404 Not found.

If I run `curl -i https://ansidev.xyz/feed.rss`, it still works.

Could we have any option for whitelisting some internal URLs that will be rendered by another tool instead of Vite?

 

### Reproduction

https://ansidev.xyz/feed.rss

### System Info

```Shell
System:
    OS: macOS 12.5
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Memory: 192.54 MB / 16.00 GB
    Shell: 3.5.1 - /usr/local/bin/fish
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 3.2.2 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Brave Browser: 102.1.39.122
    Chrome: 104.0.5112.79
    Edge: 104.0.1293.47
    Firefox: 100.0
    Firefox Developer Edition: 102.0
    Safari: 15.6
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Use `<a>` instead of `<RouterLink>`
