### ISSUE TITLE
直接注入style标签在生成的ssg的html页面

### ISSUE THREAD

**Issue by huihuilovekuikui** [antfu/vitesse#421]
### Clear and concise description of the problem

目前，打包后生成的html的css通过引入的方式
![image](https://user-images.githubusercontent.com/66559869/190679140-97d9ce0e-190e-41e9-8fe5-0dc0f124919a.png)

### Suggested solution

期望：能直接生成style标签，插入到html当中，这样能更快的看到样式

### Validations

- [x] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
This is out-of-scope of this template. You can try find some plugins for that.

**Comment by huihuilovekuikui** [comment]
> This is out-of-scope of this template. You can try find some plugins for that.
抱歉，我发现vitesse生成的css确实是在html当中，如果我在项目中只使用vite-ssg打包出来的css一个单独的文件。请问vitesse通过什么插件实现的呢？谢谢
![image](https://user-images.githubusercontent.com/66559869/190900393-95871f47-b387-4be6-849b-d4241a8cfad5.png)
![image](https://user-images.githubusercontent.com/66559869/190900401-ca7a164c-e450-4957-9b3a-eee482765c97.png)

**Comment by huihuilovekuikui** [comment]
> This is out-of-scope of this template. You can try find some plugins for that.
我已经找到原因了，是因为我如果在别的项目中引入vite-ssg，那么当我使用pnpm add vite-ssg-D时，在node_modules中，不会为下载critters，所以必须要手动下载critters
![image](https://user-images.githubusercontent.com/66559869/190901887-8f2960bd-c107-4f05-a5a9-e1c2938f9364.png)
![image](https://user-images.githubusercontent.com/66559869/190901890-e33ae791-2651-4d6c-a3a9-a54b48959402.png)
所以这是pnpm的一个bug？
