### ISSUE TITLE
BUG REPORT: hmr refresh loop when modify layout file

### ISSUE THREAD

**Issue by YunYouJun** [antfu/vitesse#425]
### Describe the bug

https://user-images.githubusercontent.com/25154432/191883539-5fc9b99e-25b3-42d5-ab69-7e507d1ca8cc.mov

The page keeps refreshing when modify files in `src/layouts`.
No other reproduce operations are required.

### Reproduction

https://github.com/antfu/vitesse

### System Info

```Shell
System:
  OS: macOS 12.6
  CPU: (10) arm64 Apple M1 Pro
  Memory: 97.03 MB / 16.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
  npm: 8.19.2 - ~/.nvm/versions/node/v16.17.0/bin/npm
Browsers:
  Chrome: 105.0.5195.125
  Firefox: 103
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zinete** [comment]
I also have this problem

**Comment by murongg** [comment]
I also have this problem

**Comment by zipme** [comment]
same here

**Comment by mrhammadasif** [comment]
It is because of `vite-plugin-vue-component-preview`, temporary workaround would be to comment `Preview()` in `vite.config.ts > plugins`

Already reported here
https://github.com/johnsoncodehk/vite-plugin-vue-component-preview/issues/9
