### ISSUE TITLE
markdown style issues

### ISSUE THREAD

**Issue by socketbear** [antfu/vitesse#426]
### Describe the bug

This is a template I use really well. I think it's the best based on Vue3, Vitejs, and I'm trying to make it more solid by adding it here and there. I am making a Korean document for education.
So the position of markdown is important. Below is a report of a markdown issue, is it possible to fix it? If not, I'd appreciate it if you could point me in the direction.

There is an issue with printing `<code>` with backticks and printing Lists. It is different from the existing markdown it, and `<code>` is a level where backticks are output together and only the font is changed. lists don't seem to have any indentation styles at all.

<img width="754" alt="스크린샷 2022-09-26 오후 2 08 02" src="https://user-images.githubusercontent.com/3022713/192197982-4756768d-2d53-4c23-b534-32dc18a455de.png">

### Reproduction

https://github.com/socketbear/vue-dev-guide/tree/2-makrdown-style-issue

### System Info

```Shell
System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 113.63 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Safari: 15.6.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
This is out-of-scope for this template. You can change to use any styles you want.
