### ISSUE TITLE
Flash on reload without cache

### ISSUE THREAD

**Issue by jbaubree** [antfu/vitesse#428]
### Describe the bug

When you are on a subpage like: `https://vitesse.netlify.app/hi/test`
If you refresh the page disabling cache with CMD + SHIFT + R, index page will be loaded before `/hi/test` page. We can see that in network render. Is this a vite-ssg issue ?
Any solution to fix this ?
<img width="778" alt="Capture d’écran 2022-09-28 à 17 22 54" src="https://user-images.githubusercontent.com/50230578/192819478-c1b50f7c-a8e2-4092-9419-c3c6d58697e2.png">

### Reproduction

https://vitesse.netlify.app/hi/test

### System Info

```Shell
Browser production env
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
https://github.com/antfu/vitesse/discussions/169

**Comment by userquin** [comment]
https://github.com/antfu/vitesse/issues/252#issuecomment-1046085093

**Comment by jbaubree** [comment]
Oh thanks, sorry for duplication
