### ISSUE TITLE
alias with ~ error in <img /> usage

### ISSUE THREAD

**Issue by aimergenge** [antfu/vitesse#429]
### Describe the bug

In the `src/pages/index.vue`, I reference `src/static/pwa.png` via `<img src="~/static/pwa.png" />`, which report an error said:
<img width="923" alt="image" src="https://user-images.githubusercontent.com/13799160/193000788-7daab6b2-2f5c-46c9-b462-5814e9bd4014.png">

### Reproduction

https://github.com/aimergenge/vitesse

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 72.88 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 105.0.1
    Safari: 16.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aimergenge** [comment]
But If I add a same record(but replace `~` with `@`) to `resolve.alias`:
```
resolve: {
  alias: {
    '~/': `${path.resolve(__dirname, 'src')}/`,
    '@/': `${path.resolve(__dirname, 'src')}/`,
  },
},
```
And replace `<img src="~/static/pwa.png" />` with `<img src="@/static/pwa.png" />`, it just works!

**Comment by aimergenge** [comment]
Closed because I think it's caused by `vite` or `@vitejs/plugin-vue`

**Comment by warmthsea** [comment]
If used in this way, the ctrl+click path is incorrect, and there is no syntax prompt for input
![image](https://user-images.githubusercontent.com/45450994/223657357-af359d4b-2260-46f2-964c-1caed8e3cf13.png)
![image](https://user-images.githubusercontent.com/45450994/223657424-895df4c8-560c-4b93-99a4-447cfce258c3.png)
![image](https://user-images.githubusercontent.com/45450994/223657599-ba0d11b2-8464-4880-89de-cb01aab65a90.png)
