### ISSUE TITLE
unjs/head@v1.1.0 changed thier schema, resulting in @vueuse/head schema being incorrect and an empty title tag on SSG render

### ISSUE THREAD

**Issue by Saganic** [antfu/vitesse#478]
### Describe the bug

[unjs/head@v1.10](https://github.com/unjs/unhead/releases/tag/v1.1.0) released a new schema for title definition, that causes vitesse to render an empty title tag with vite SSG. 

### Reproduction

https://github.com/antfu/vitesse/

### System Info

```Shell
System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 12.34 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.4.0 - ~/.nvm/versions/node/v18.4.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.6.1 - ~/.nvm/versions/node/v18.4.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 106.0.5
    Safari: 15.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment]
Hey @Saganic 

Can you provide some details on the issue? Ideally a Stackblitz reproduction.

I've pulled down the Vitesse and ran `pnpm build` and it looks like the title is generated correctly.

`<title>Vitesse</title>`

Also, the way you're describing the issue isn't accurate, title schema remains the same within v1.1. No breaking changes were introduced afiak.
