### ISSUE TITLE
When using the ant-design-vue button, the button background-color is overwritten by the reset style.

### ISSUE THREAD

**Issue by lessroc** [antfu/vitesse#484]
### Describe the bug

Here: /node_modules/.pnpm/@unocss+reset@0.50.6/node_modules/@unocss/reset/tailwind.css

/*
1. Correct the inability to style clickable types in iOS and Safari.
2. Remove default button styles.
*/

button,
[type='button'],
[type='reset'],
[type='submit'] {
  -webkit-appearance: button; /* 1 */
  background-color: transparent; /* 2 */
  background-image: none; /* 2 */
}

### Reproduction

pnpm i --save ant-design-vue; use button

### System Info

```Shell
System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 4.93 GB / 15.92 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan ([0x7FFA1D064F90] ANOMALY: meaningless REX prefix used
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
use `@unocss/reset/tailwind-compact.css` instead
