### ISSUE TITLE
 PrimeVue: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by vincenzomartusciello** [antfu/vitesse#488]
### Describe the bug

Hi, I have this problem, I just did this:
- Downloaded the teamplate
- Done `npm install primevue`
- Added a module `privevue.ts`

```
import PrimeVue from 'primevue/config'
import { type UserModule } from '~/types'

export const install: UserModule = ({ app }) => {
  app.use(PrimeVue)
}
```

- Then I execute `vite-ssg build`

With `vite build` I have no problem

### Reproduction

None

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13600K
    Memory: 11.34 GB / 31.77 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1555.0), Chromium (112.0.1722.48)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
The issue tracker is not "free support", please show some respect. Thanks.
