### ISSUE TITLE
Linting issue: Type '_ActionsTree' is missing (pinia store)

### ISSUE THREAD

**Issue by Borderliner** [antfu/vitesse#490]
### Describe the bug

I'm getting this error on the basic `user.js` store which comes with this project:
```
Argument of type 'StoreDefinition<"user", _UnwrapAll<Pick<{ setLoggedIn: (flag: boolean) => void; setName: (userName?: string | undefined) => void; setEmail: (userEmail?: string | undefined) => void; setApiKey: (userApiKey?: string | undefined) => any; ... 7 more ...; getUser: ComputedRef<...>; }, never>>, Pick<...>, Pick<...>>' is not assignable to parameter of type 'StoreDefinition<string, StateTree, _GettersTree<StateTree>, _ActionsTree>'.
  Type '_ActionsTree' is missing the following properties from type 'Pick<{ setLoggedIn: (flag: boolean) => void; setName: (userName?: string | undefined) => void; setEmail: (userEmail?: string | undefined) => void; setApiKey: (userApiKey?: string | undefined) => any; ... 7 more ...; getUser: ComputedRef<...>; }, "setLoggedIn" | ... 3 more ... | "setUser">': setLoggedIn, setName, setEmail, setApiKey, setUserts(2345)
```

AFAIK it's something related to hydration. But how do I get rid of this linting problem so that it doesn't cause problems in the future.

### Reproduction

Clone the repo, run eslint

### System Info

```Shell
System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 3.90 GB / 15.57 GB
    Container: Yes
    Shell: 3.3.1 - /usr/bin/fish
  Binaries:
    Node: 18.16.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.5.1 - /usr/bin/npm
  Browsers:
    Chrome: 112.0.5615.165
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
I am not able to reproduce it. Please provide more information.

**Comment by Borderliner** [comment]
Can't reproduce it either since today. Seems to be gone somehow. I'll post updates if anything comes up. Let's close this issue for now.
