### ISSUE TITLE
When I use markdown as the page, the code block shows both themes, because is it an example?

### ISSUE THREAD

**Issue by Carina957** [antfu/vitesse#495]
#### Code source

<br>

> no code modification

```sh
degit antfu/vitesse my-vitesse-app
ni
nr dev
```

#### Sample image

<br>

![image](https://github.com/antfu/vitesse/assets/56385216/76feda10-4cf2-4074-8a4d-744a5ab00909)

#### At last

<br>

By the way,  i'm a big fan of Mr Anthony Fu.

### Reproduction

The test above

### System Info

```Shell
System:
  OS: Windows 10 10.0.19044
  CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz   
  Memory: 718.49 MB / 7.89 GB
Binaries:
  Node: 16.19.0 - C:\Program Files\nodejs\node.EXE
  Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
  npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
Browsers:
  Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.35)
  Internet Explorer: 11.0.19041.1202
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
I am not able to reproduce it, neither the live deployment: https://vitesse.netlify.app/about

**Comment by Carina957** [comment]
Here is the reproduction: 

- [Github](https://github.com/Carina957/vitesse-issues495-reproduction)
- [Reproduction address](https://carina957.github.io/about)

**Comment by Carina957** [comment]
In the latest version, it seems to have been fixed.
