### ISSUE TITLE
[feature request]  layout feature

### ISSUE THREAD

**Issue by yaquawa** [antfu/vitesse#50]
Hi, great works on this!!

Providing layout feature just like nuxt.js would be very helpful.
I'm wondering if it is even possible to have such feature in vite.
Do you have any suggestion on how to do this?
Thanks!!

**Comment by JohnCampionJr** [comment]
I've been working on this very thing.  See my branch here. 

https://github.com/JohnCampionJr/vitesse/tree/layout

Also working on a PR for the auto route generator that allows adding route data in the SFC which will allow for easy layout overrides.

**Comment by yaquawa** [comment]
Wow! Thanks for that!!
it'll be nice if there's explanation on the readme.md.

**Comment by antfu** [comment]
@JohnCampionJr Just saw the PR get merged and release 🎉. I think this is a good feature to have, are you interested in creating a PR for Vitesse to set up the layouts? Thanks!

**Comment by JohnCampionJr** [comment]
Yes, definitely.  Will do ASAP!

**Comment by yaquawa** [comment]
@JohnCampionJr Cool!! Thanks!!
