### ISSUE TITLE
Composable syntax 

### ISSUE THREAD

**Issue by jakubserwin** [antfu/vitesse#500]
### Describe the bug

The `@antfu/eslint-config-vue` extends `@antfu/eslint-config-basic` in which there is a rule `'antfu/top-level-function': 'error',`. Because of that, ESLint throws an error when you try to write composable using ES6 syntax. 

![Screenshot 2023-05-31 at 07 31 30](https://github.com/antfu/vitesse/assets/68373864/1a8f6e4a-e677-4b8e-b95b-4d17b112171c)

### Reproduction

Create composable following ES6 syntax

### System Info

```Shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 100.47 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.9.0 - ~/.nvm/versions/node/v19.9.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.6.3 - ~/.nvm/versions/node/v19.9.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 113.0.2
    Safari: 16.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
It's not about ES6. And it's just an opinionated rule, you can always disable it.
