### ISSUE TITLE
Font inconsistency between local run and online demo

### ISSUE THREAD

**Issue by nailuox** [antfu/vitesse#505]
### Describe the bug

The font after local operation is inconsistent with the online demo, and the packaged font is the same as the online demo

local run: 
![image](https://github.com/antfu/vitesse/assets/49058926/92abd864-ec18-4587-94b6-ababdcc11f22)
![image](https://github.com/antfu/vitesse/assets/49058926/6dc39fcf-e29f-456b-aa84-98e74b57ce8c)

online demo:
![image](https://github.com/antfu/vitesse/assets/49058926/d8bf5de4-63fe-4829-a0fb-3dc1f8a869fa)

package: 
![image](https://github.com/antfu/vitesse/assets/49058926/95ee47dd-8402-4aa2-8911-e5d1d411a363)

### Reproduction

no

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 2.04 GB / 15.77 GB
  Binaries:
    Node: 16.18.1 - D:\soft\nvm\nodejs\node.EXE
    Yarn: 1.22.19 - D:\soft\nvm\nodejs\yarn.CMD
    npm: 8.19.2 - D:\soft\nvm\nodejs\npm.CMD
    pnpm: 8.6.10 - D:\soft\nvm\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (115.0.1901.200)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kevinmarrec** [comment]
I can confirm that `WebfontDownload` Vite plugin is not working with `presetWebFonts` of UnoCSS, resulting in a production build without extracted fonts.
