### ISSUE TITLE
[Question] can we delegate one route to a completely independent app (similar to single-spa, sort of...)

### ISSUE THREAD

**Issue by Codermar** [antfu/vitesse#51]
Hi Anfu, thanks for the awesome work you did with this template.

I am considering using it in my next project in a scenario similar to this:

**root-portal-app** (vitesse app)
 - **index** (landing public page)
   - other public pages and markdown files
 - **docs/index** (landing page for docs)
   - other public doc pages and markdown files
 - **legacy-vue-2-app** via git submodule that runs standalone (with auth). Let's say this is a "projects" directory so any route starting with /project would have to be "relayed" to the legacy app which does have authentication. (we would not want auto-generated routes in this directory

Is this scenario possible to do with vitesse being the top app?

Ideally, in the future I would like to start migrating the legacy app (basically route by route or feature by feature) into Vue 3 in the vitesse realm. This is kind of a similar concept of [vue-microfrontends](https://github.com/vue-microfrontends) and single-spa without the whole microfrontend stuff.

Please let me know your thoughts.

**Comment by antfu** [comment]
For the build, I think you can just copy the dist from the two sites and put them together under the directory. For the dev you might need to use the proxy option in Vite. I personally don't have much experience on this and it's out-of-scope of Vitesse. You can try asking this in discord or GitHub discussion of Vite.
