### ISSUE TITLE
Consider using `unplugin-vue-router`

### ISSUE THREAD

**Issue by Dimava** [antfu/vitesse#510]
### Clear and concise description of the problem

https://github.com/hannoeru/vite-plugin-pages says:
> 
> ### Vue
> 
> **🚨Important Notes🚨**
> 
> We recommend Vue user using [unplugin-vue-router](https://github.com/posva/unplugin-vue-router) instead of this plugin.
> 
> [unplugin-vue-router](https://github.com/posva/unplugin-vue-router) is a unplugin library created by [@posva](https://github.com/posva), same auther as vue-router. It provide almost same feature as [vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages) but better intergration with vue-router, include some cool feature like auto generate route types base on your route files to provide autocomplete for vue-router.

https://github.com/posva/unplugin-vue-router however says:
> ⚠️ This package is still experimental. If you found any issue, design flaw, or have ideas to improve it, please, open an [issue](https://github.com/posva/unplugin-vue-router/issues/new/choose) or a [Discussion](https://github.com/posva/unplugin-vue-router/discussions).

### Suggested solution

Check out https://github.com/posva/unplugin-vue-router, compare it to `vite-plugin-pages`, and consider
- if it worth replacing `vite-plugin-pages` with `unplugin-vue-router` now
- if it worth replacing `vite-plugin-pages` with `unplugin-vue-router` after `unplugin-vue-router` reaches `v1.0`

### Alternative

If it would be concluded there is no point in migration, write the reasoning in a comment and close the issue, so people can find the issue and don't ask the same question again

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Definitely, PR welcome :)
