### ISSUE TITLE
Is there a plan to support jsx?

### ISSUE THREAD

**Issue by whoooami** [antfu/vitesse#521]
### Clear and concise description of the problem

.

### Suggested solution

.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
No, it's a template after all, feel free to install it yourself.

**Comment by whoooami** [comment]
> No, it's a template after all, feel free to install it yourself.

got it, thx.

**Comment by whoooami** [comment]
Sorry to both again, After I changed [...all].vue to [...all].jsx, eslint kept reporting errors. Below are the corresponding results for 404.jsx and the corresponding pnpm lint. 
### 404.jsx
```
import { defineComponent } from 'vue'

export default defineComponent({
  // name: '404Page',
  setup() {
    // your setup code here
    const { t } = useI18n()
    // eslint-disable-next-line unused-imports/no-unused-vars
    const { route } = useRoute()

    return () => (
      <>
        <div>
          { t('not-found') }
        </div>
        <route lang="yaml">
        meta:
          layout: 404
        </route>
      </>
    )
  },
})
```
### pnpm lint result
```
  16:28  error  Expected indentation of 10 space characters but found 8   style/jsx-indent
  16:28  error  Expected indentation of 10 space characters but found 10  style/jsx-indent
```

I tried for half a day and couldn't find a solution that use eslint ignored the problem. If it's convenient for you, please help me take a look. Thanks again.
