### ISSUE TITLE
Security improvement hints

### ISSUE THREAD

**Issue by userquin** [antfu/vitesse#59]
@antfu I think it would be a good practice to include some security improvements to instruct people to do things a little more secured.

A first step would be to include a CSP here, very simple without complex things.

For example, I use [WebPageTest](https://www.webpagetest.org/) to audit my applications, a step further Lighthouse (this is the result for vitesse demo, I have included https://github.com/antfu/vitesse/issues/58#issue-806879992 to optimize png icons):

![vitesse-webpagetest](https://user-images.githubusercontent.com/6311119/107720902-a366e800-6cdb-11eb-9832-3cea41567b86.png)

The goal is to get something like this (my app is still in our servers, so the CDN entry is good here, using netlify):

![imagen](https://user-images.githubusercontent.com/6311119/107721205-5d5e5400-6cdc-11eb-884e-e9eeda84f0b8.png)

A simple CSP I get working with vitesse demo (not perfect) will be to add this header at least for /:

```html
'content-security-policy': "default-src 'self'; connect-src 'self'; font-src 'self'; manifest-src 'self'; img-src 'self'; frame-src none; worker-src 'self'; base-uri 'self'; child-src 'self'; frame-ancestors 'none'; object-src 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'"
```

`'unsafe-eval'` on `script-src` is required due to `i18n`: see this https://github.com/intlify/vue-i18n-next/issues/198

We also need to include these headers, at least for /:
```html
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1 ; mode=block
```

and this header for all resources:
```html
x-content-type-options: nosniff
```

A more complex sample will be to use nonce, but this will force us to change html files and do some server scripting (in fact entire CSP will change in this case, so don't try):

For example, using this CSP `script-src`:
```html
script-src 'unsafe-inline' 'nonce-9b03dfef-98aa-42d9-89ad-3ce2dc57ffd3' 'strict-dynamic' https:;
```
will prevent to execute this script from `index.html`:
```html
<script>
    (function() {
      const prefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches
      const setting = localStorage.getItem('color-schema') || 'auto'
      if (setting === 'dark' || (prefersDark && setting !== 'light'))
        document.documentElement.classList.toggle('dark', true)
    })()
  </script>
```

and we need to change dynamically for each request to (also the CSP `script-src` nonce entry for each request and add the same nonce entry to each `<script src="xxx" nonce="zzzzz">` tag):
```html
<script nonce="9b03dfef-98aa-42d9-89ad-3ce2dc57ffd3">
    (function() {
      const prefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches
      const setting = localStorage.getItem('color-schema') || 'auto'
      if (setting === 'dark' || (prefersDark && setting !== 'light'))
        document.documentElement.classList.toggle('dark', true)
    })()
  </script>
```

You can see a working sample here: https://covid19desa.saludcontigo.co:33013 (made with vite 1 + polymer 3 webcomponents + vue components). Nonces are hidden from devtool elements tab, to see it you need to open network tab and see source.

**Comment by antfu** [comment]
Thanks for looking into it. Indeed it's good to have better security scores, but I think it introduced too much friction but little to gain in this particular template. The inline script makes sure that dark mode is updated with the initial rendering (UX) while using `nonce` will make the script hard to modify (DX). This could deviate from the initial purpose of having a starter template. I think it's better to apply the security practices from the template users side based on their needs, rather than the template itself. Thanks for the tips and I believe someone would find this issue useful. Close as I think out-of-scope of this template.

**Comment by userquin** [comment]
@antfu I agree with you, but I'm suggest to include the simple csp, not nonce based, due to the complexity it requires.

**Comment by antfu** [comment]
> include the simple csp

Sounds good, would you like to create a PR? Thanks

**Comment by userquin** [comment]
Of course, I'm working on it, I need to finish some enterprise work...

@antfu I am reviewing pwa plugin to include `New content available + REFRESH` missing feature here, how can I integrate with this template?
I meant, I'm changing PWA plugin to notify update + changed events (based on [register-service-worker](https://github.com/yyx990803/register-service-worker) repo).
In the other hand, I'm thinking to include it on `@vueuse`, something like `useServiceWorker` function, but I need to sort out a bit how it's going to be integrated first.
Some hints are welcome...

**Comment by antfu** [comment]
> pwa plugin to include New content available + REFRESH missing feature

Yeah, that's something I want to do for a while. But haven't look into it yet. It would be great if you would like to give it a try!

> I'm thinking to include it on @vueuse, something like useServiceWorker function

Sounds good!

PWA is not my focus currently, but eventually, I will have a look and implement it. Sorry as I can't help you on this atm, but maybe you can draft some PRs so I can help to review it. Thanks!

**Comment by antfu** [comment]
PS. Commonly I don't read notifications from a close issue, if you would like to keep the discussion, it's better to open another issue instead. `vite-plugin-pwa` could also be a better place.

**Comment by userquin** [comment]
OK, and sorry to bother you again...
