### ISSUE TITLE
Use purgecss to limit only used tailwind CSS

### ISSUE THREAD

**Issue by iamareebjamal** [antfu/vitesse#6]
Currently, the site loads 2.7 MB(200 KB) compressed CSS. The advantage of utility only CSS library like tailwind is that you only load what you use, and thus purgecss should be used to limit the CSS bundled to only the classes being used

**Comment by antfu** [comment]
I thought the purge for tailwind css is enabled by default when the config is set. It turns out that I need to set the `enabled` explicitly. Just fixed and thanks for the catch-up!

**Comment by iamareebjamal** [comment]
Great! Reduced to just 9 KB now! Awesome!
