### ISSUE TITLE
__DEFINES__ is not defined

### ISSUE THREAD

**Issue by husayt** [antfu/vitesse#64]
Since last week I have been getting the following error in the browser when doing `pnpm dev`:

```
env.js:3 Uncaught ReferenceError: __DEFINES__ is not defined
    at env.js:3
```

That code is part of vite `http://localhost:3333/node_modules/.pnpm/vite@2.0.0-beta.69/node_modules/vite/dist/client/env.js`, not sure why/how it gets to browser?

Os: Win10
node: 14.15.3

**Comment by antfu** [comment]
Can't repro, please provide a minimal reproduction with the latest dependencies.

**Comment by husayt** [comment]
İ just download the template, do `pnpm i` and `pnpm dev`, nothing else
