### ISSUE TITLE
[bug]Markdown file with specified layout will render extra text.

### ISSUE THREAD

**Issue by Ynewtime** [antfu/vitesse#67]
## Bug report

Markdown file with [specified layout](https://github.com/JohnCampionJr/vite-plugin-vue-layouts#overview) will render extra text.

1、Add a new page like `pages/test.md`

```markdown
Hello World

<route lang="yaml">
meta:
  layout: home
</route>
```

![](https://raw.githubusercontent.com/Ynewtime/vitesse-md-with-layout/master/public/screenshot1.png)

2、Can avoid by adding a `hidden` class:

```markdown
Hello World

<route lang="yaml" class="hidden">
meta:
  layout: home
</route>
```

![](https://raw.githubusercontent.com/Ynewtime/vitesse-md-with-layout/master/public/screenshot2.png)

## Reproduction repo

[vitesse-md-with-layout](https://github.com/Ynewtime/vitesse-md-with-layout)

**Comment by hannoeru** [comment]
You can't just write custom block to markdown file because it will transform into `<template>/* here */</template>`,
there is a option in `vite-plugin-pages` call `extendRoute`, which can add some custom meta using:
```ts
// vite.config.js plugin
Pages({
  extendRoute: (route) => {
    if (route.component.endsWith('pages/test.vue')) {
      route.meta.layout = 'home'
    }
  }
})

**Comment by Ynewtime** [comment]
@hannoeru  Yah I got it, thanks. So is there another way to specify custom layout directly inside of a markdown file? I tried YAML meta head just like how jekyll does, and it doesn't work as expected. Maybe I should check out the markdown plugin source code.

**Comment by JohnCampionJr** [comment]
Would it be a big change for the vite-markdown plugin to strip out the route block?

**Comment by Hebilicious** [comment]
Following up on @hannoeru comment, the following code worked for me
```ts
        Pages({
            extensions: ['vue', 'md'],
            extendRoute: (route) => {
                console.log(route)
                if (/.*\/mydirname\/.*\.md/.test(route.component)) {
                    route.meta = { layout: 'mylayout' }
                }
            },
        }),
```

**Comment by hannoeru** [comment]
With vite-plugin-md v0.5.0, now you can write route custom block inside markdown file!!

markdown:
```md
# Hello World

<route lang="yaml">
meta:
  layout: home
</route>
```
