### ISSUE TITLE
[Bug]css.gg icons cannot be auto imported as others.

### ISSUE THREAD

**Issue by Ynewtime** [antfu/vitesse#68]
## Bug report

css.gg icons cannot be auto imported as others.

## Reproduction

1. Open `src/components/Footer.vue`, replace `carbon-sun` with `gg-sun`(Or replace any other icon with [css.gg](https://icones.js.org/collection/gg) icon)
2. `pnpm dev`
3. Check the devtools console

![](https://github.com/Ynewtime/vitesse-icon-gg/raw/master/public/vitesse-gg-icon-bug.png)

## Reproduction repo

https://github.com/Ynewtime/vitesse-icon-gg

**Comment by antfu** [comment]
Uhm, it's working with the latest Vitesse

![image](https://user-images.githubusercontent.com/11247099/108594177-55c13e00-73b3-11eb-9ffa-a71cbecdc0e4.png)
![image](https://user-images.githubusercontent.com/11247099/108594184-5ce84c00-73b3-11eb-8950-241fd45b730f.png)

**Comment by Ynewtime** [comment]
That's weird. Still not working in my machine with the latest release.

<img width="718" alt="截屏2021-02-20 下午2 52 43" src="https://user-images.githubusercontent.com/27655771/108594558-bd639300-738b-11eb-8835-cccd693739eb.png">

machine: macOS 11.3 Beta(20E5186d)
nodejs version: v15.9.0
package manager: pnpm 5.17.2
reproduction repo: https://github.com/Ynewtime/vitesse-test

**Comment by antfu** [comment]
It seems like you forget to commit your changes to your repro. But still, I pull down and it works.

**Comment by antfu** [comment]
I am using the same version of both Node and pnpm, but with macOS 11.2 if that matters.

**Comment by hannoeru** [comment]
Try to use incognito mode to open it.

**Comment by Ynewtime** [comment]
@antfu  Sorry I forgot to push the commit 😅.

More information: I test it with an Apple M1 machine, MBA with 8GB, and I install the nodejs with `nvm i v15.9.0` which was built from the source code.

@hannoeru  It works! With incognito mode of Chrome it works as expected.

<img width="1440" alt="截屏2021-02-21 上午7 56 49" src="https://user-images.githubusercontent.com/27655771/108616016-9ef8a880-741a-11eb-8296-241fc7b22194.png">

But still it only works for Chrome incognite mode, Chrome/Safari/Safari incognite mode show the same error.

<img width="1440" alt="截屏2021-02-21 上午7 57 48" src="https://user-images.githubusercontent.com/27655771/108616094-72915c00-741b-11eb-8aa2-78b789215042.png">

**Comment by hannoeru** [comment]
I think is some thing like AD blocker blocked it. Can you also try to turn off firewall or any antivirus software?

**Comment by antfu** [comment]
Might be some adblocker false-positive, close as its not related to this plugin.

**Comment by Ynewtime** [comment]
After turning off my [adblocker](https://chrome.google.com/webstore/detail/%E5%B9%BF%E5%91%8A%E7%BB%88%E7%BB%93%E8%80%85/fpdnjdlbdmifoocedhkighhlbchbiikl) extension on Chrome it works! And for Safari you can go to `View -  Reload without content blockers`.

But still, why is it just css.gg icon set? Every other icon set I tested with this plugin works but only css.gg prompts the error.

**Comment by antfu** [comment]
> But still, why is it just css.gg icon set? Every other icon set I tested with this plugin works but only css.gg prompts the error.

You can have a look at its rules. But either way, it's out-of-scope of this project.
