### ISSUE TITLE
Cannot import an interface in a Page

### ISSUE THREAD

**Issue by pierresaid** [antfu/vitesse#82]
Repro : 

* `npx degit antfu/vitesse my-vitesse-app`
* Create `src/models` folder
* Create `src/models/test.ts` file

```typescript
// test.ts
export interface Test {
  id: number
}
```

In `src/pages/index.vue` 

add in script :

```typescript
// index.vue
import { Test } from '~/models/test'
```

This error pop up with a blank page : 

`Uncaught SyntaxError: The requested module '/src/models/test.ts' does not provide an export named 'Test'`

Thank you.

**Comment by hannoeru** [comment]
Use ￼`import type { Test } from '~/module/test'`

**Comment by pierresaid** [comment]
This works thank you do you have some links on some documentation or why is it like this ?

**Comment by skyrpex** [comment]
It's a typescript thing. If you only import a type from a module, you need specify that it's a type. I think it's only necessary if you're transpiling your code to JS.
