### ISSUE TITLE
help: 't' is declared but its value is never read.Vetur(6133)

### ISSUE THREAD

**Issue by carlomigueldy** [antfu/vitesse#83]
![image](https://user-images.githubusercontent.com/45052332/110196269-632ffb00-7e7e-11eb-9a5d-4823ff3a1ed3.png)

Hi, what do you guys suggest I should do? I don't wanna put `// @ts-ignore` everytime I see something like that if it's possible

**Comment by hannoeru** [comment]
Did you enabled volar and volar's tsPlugin option?

**Comment by carlomigueldy** [comment]
> Did you enabled volar and volar's tsPlugin option?

No. I didn't even know about that. Where do I enable it?

**Comment by hannoeru** [comment]
Just install volar
https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar
then it should works.

**Comment by antfu** [comment]
Yep, we recommend to use Volar for this project. Thanks.

**Comment by carlomigueldy** [comment]
Thanks!
