### ISSUE TITLE
help: Prettier cannot format code

### ISSUE THREAD

**Issue by carlomigueldy** [antfu/vitesse#87]
![image](https://user-images.githubusercontent.com/45052332/111052318-bb758700-8494-11eb-8854-871af4515e0a.png)

I am using the Volar extension. But I can't auto format the code. Does anyone else encountered and fixed this issue?

**Comment by antfu** [comment]
I don't use Prettier and disabled it explicitly in the `.vscode/settings.json`. Reason see https://github.com/vueuse/vueuse/issues/237

**Comment by carlomigueldy** [comment]
By the way is there a Discord channel? @antfu
