### ISSUE TITLE
File based routing feedback

### ISSUE THREAD

**Issue by Drumstix42** [antfu/vitesse#88]
In reference to this https://github.com/antfu/vitesse/blob/master/src/pages/README.md

I've seen the `~` prefix used before and it has been used to reference the `node_modules` folder (e.g. Webpack). This is a bit confusing with this starter.

Another way I've seen a way to reference the `./src` folder is to use the `@` prefix.

So that means that this:
```
import { isDark } from '../../../../logics'
```

Becomes this:
```
import { isDark } from '@/logics'
```

Thoughts?

**Comment by antfu** [comment]
Can you share the reference of using `~` for `node_modules`? I don't think it makes sense to me as by default you are already import modules from `node_modules`.

**Comment by Drumstix42** [comment]
Perhaps this is only a default for CSS styles actually.

E.g.
```
@import "~normalize/normalize.css";
```

I agree with that for JS it already defaults to `node_modules` when you don't specify a path.

**Comment by antfu** [comment]
The solution for `css-loader` feels a bit weird to me. But in Vite, the `@import` works the same as js modules without the `~` prefix to use modules. And the alias is also respected.

See:
https://vitejs.dev/guide/features.html#import-inlining-and-rebasing
https://github.com/postcss/postcss-import#usage

Thanks for bringing this up. As this is just a preference, I would keep going with `~/` for this template.
