### ISSUE TITLE
'React' must be in scope when using JSX react/react-in-jsx-scope

### ISSUE THREAD

**Issue by rainmanhhh** [antfu/vitesse#91]
even if I add rule `"react/react-jsx-in-scope": 0` in .eslintrc it still reports this error, how to fix it?

**Comment by hannoeru** [comment]
Vitesse is a Vue template, so I think this is not related to this repo, can you provide more context?

**Comment by rainmanhhh** [comment]
vue supports tsx. my component:
```
import { defineComponent, reactive } from 'vue'

export const Foo = defineComponent({
  name: 'Foo',
  props: {
    isEnabled: {
      type: Boolean,
      required: true
    }
  },
  setup() {
    const s = reactive({
      value: false,
      toggle() {
        s.value = !s.value
      }
    })
    return s
  },
  render() {
    return <div onClick={this.toggle}>foo.isEnabled: {String(this.value)}</div> // idea reports eslint error here
  }
})
```

**Comment by hannoeru** [comment]
Add `"react/react-in-jsx-scope": "off"` to `.eslintrc`,
then add vite-vue-jsx plugin
https://github.com/vitejs/vite/tree/main/packages/plugin-vue-jsx
to vite config.
