### ISSUE TITLE
i18n with SSG?

### ISSUE THREAD

**Issue by MartinMalinda** [antfu/vitesse#94]
I'm wondering how to approach i18n with SSG, having `/{locale}/` namespace in the URL.

I guess that's something out of scope for vitesse to do on its own? Too opinionated approach already?

Afaik there's three potential things to do:

1) Add a locale route
2) Add meta tags for alternative URLs
3) Language detection -> redirection

I'm curious if someone else was dealing with this already

**Comment by antfu** [comment]
Haven't tried myself yet, but I have been told there is a solution that works.

https://discord.com/channels/804011606160703521/804061937029218334/821401133419069460

If you want to make Vitesse support i18n that way, I will be happy to receive a PR, thanks!

**Comment by MartinMalinda** [comment]
I have some WIP, I'll see to what degree it can be generalized and merged into `vitesse`. If anything, I can add a note into `README.md` with a few pointers.

**Comment by MartinMa** [comment]
That would be a huge improvement.

@antfu I cannot access the Discord link. Which Discord server are you referring to?

**Comment by hannoeru** [comment]
@MartinMa You need to join vite's discord server first, here is the link: https://chat.vitejs.dev/

**Comment by userquin** [comment]
@MartinMalinda some news on this?

**Comment by MartinMalinda** [comment]
I've summarized my solution here: https://github.com/antfu/vite-ssg/discussions/58#discussioncomment-889263

**Comment by antfu** [comment]
Close in favor of https://github.com/antfu/vite-ssg/discussions/58

**Comment by userquin** [comment]
https://github.com/antfu/vite-ssg/discussions/58#discussioncomment-920967
