### ISSUE TITLE
Type checking in "Dev Server Console" like Vue CLI

### ISSUE THREAD

**Issue by pingustar** [antfu/vitesse#98]
First, really great job with this template @antfu ! Got me up and running in no time.

Only thing I kind a miss is the type checking feature for the dev server console like we have when using Vue CLI to bootstrap a project. See screenshots for example of what I mean.

I am generally interested if this is even possible with Vite. And if so, I would very much appreciate if you could point me in the right direction on how to get that implemented.

Thanks!

![image](https://user-images.githubusercontent.com/7262066/111805191-195d0100-88d1-11eb-9df7-113c2eb826f3.png)
![image](https://user-images.githubusercontent.com/7262066/111805835-b15aea80-88d1-11eb-8b5d-a3f07374194c.png)

**Comment by antfu** [comment]
Vite's notion is that [`It assumes type checking is taken care of by your IDE and build process`](https://vitejs.dev/guide/features.html#typescript).

But maybe you can try [vue-tsc](https://github.com/johnsoncodehk/vue-tsc).

**Comment by pingustar** [comment]
> Vite's notion is that [`It assumes type checking is taken care of by your IDE and build process`](https://vitejs.dev/guide/features.html#typescript).
> 
> But maybe you can try [vue-tsc](https://github.com/johnsoncodehk/vue-tsc).

Thanks!
